SELECT
	ETP_ID 
FROM
	T_ENTERPRISE_INFO_TD 
WHERE
	ETP_NAME LIKE '北京亦胜%'
	ETP_NAME = '宁波银行wuc个人测试公司';

INSERT INTO `open_service_dev`.`O_THIRD_SYS_API_TB`(`API_ID`, `API_NAME`, `API_URL`, `SYS_ID`, `TRANS_CODE`, `API_METHOD`, `API_STATE`, `CREATE_TIME`, `CONTEXT_TYPE`) VALUES ('A1000000000106', '获取飞书证件类型', 'corehr/v1/national_id_types', 'S1000000000012', 'feishu/getNationalType', 'GET', '1', '2024-06-05 08:17:00', NULL);



INSERT INTO fuyao_user_dev.ENT_HR_ARCHIVE_BASIC_INFO_TD (
EMP_NO,
ID_NAME,
ID_NUMBER,
CREATE_TIME,
LAST_MODI_TIME 
)
VALUES
	(
	"Dfs1a37c9ecc304cc6e6738eb79f0af4f071",
	"周建国",
	upper( "110101199910010119"  ),
	
	SYSDATE( ) ,
	
	SYSDATE( ) 
	) 
	ON DUPLICATE KEY UPDATE ID_NAME =
VALUES
	( ID_NAME ),
	ID_NUMBER =
VALUES
	( ID_NUMBER ),
	LAST_MODI_TIME =
VALUES
	( LAST_MODI_TIME );

SELECT
	* 
FROM
	app_market_dev.SYS_MENU SM 
WHERE SM.DEL_FLAG != '0' 
and SM.MENU_TYPE != '0' 
ORDER BY
	SM.SORT ASC;


SELECT
	*
FROM
	( SELECT EMP_ID,name FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE ETP_ID = 'C2311231147301838934081353555974' AND VALID = 'A' ) TCIT
	LEFT JOIN fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT ON TCIT.EMP_ID = EHWIT.EMP_NO 
WHERE
	EHWIT.POSITIONS = 'C2311231846491839039602944700418';



	SELECT
EHLOIT.ETP_ID,
TCIT.PHONE,
ENTRY_BLACKLIST.ID,
ENTRY_BLACKLIST.EMP_PHONE,
	EHLOIT.ID AS EMP_NO,
	EHLOIT.EMP_NAME AS NAME,
	EHLOIT.DEPART_ID AS DEP_ID,
	EHLOIT.PHONE,
	IFNULL( EEDIT.DEP_NAME, '宁波银行wuc个人测试公司' ) AS DEP_NAME,
	EHLOIT.JOB_TITILE,
	EHWIT.ENTRY_TIME AS ENTRY_DATE,
	EHWIT.REGULAR_WORKER_DATE,
	EHLOIT.DIMISSION_DATE,
	EHWIT.EMP_TYPE,
	EHLOIT.REASONS_LEAVING,
	EHLOIT.REASONS_LEAVING_1,
	EHLOIT.REASONS_LEAVING_2,
CASE
	SUBSTRING( TCIT.EMP_NO, 1, 2 ) 
	WHEN 'WW' THEN
	'企微' 
	WHEN 'dt' THEN
	'钉钉' 
	WHEN 'fs' THEN
	'飞书' ELSE
CASE
	SUBSTRING( TCIT.EMP_NO, 1, 3 ) 
	WHEN 'QWD' THEN
	'企微' 
	WHEN 'kfp' THEN
	'泛微' 
	WHEN 'dyr' THEN
	'DBOX' ELSE '' 
END 
	END AS CHANNEL,
	EHLOIT.NOTE,
CASE
	WHEN TRIM( ENTRY_BLACKLIST.EMP_PHONE ) IS NULL 
	OR TRIM( ENTRY_BLACKLIST.EMP_PHONE ) = '' THEN
	'1' ELSE '0' 
	END AS IS_BLACK 
FROM
	fuyao_user_dev.ENT_HR_LEAVE_OFFICE_INFO_TD EHLOIT
	LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD TCIT ON EHLOIT.ID = TCIT.EMP_ID
	LEFT JOIN fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT ON EHWIT.EMP_NO = EHLOIT.ID
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT ON EEDIT.ETP_ID = EHLOIT.ETP_ID 
	AND EEDIT.DEP_ID = EHLOIT.DEPART_ID 
	AND EEDIT.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.ENT_ENTRY_BLACKLIST_TD ENTRY_BLACKLIST ON EHLOIT.ETP_ID = ENTRY_BLACKLIST.ETP_ID 
	AND TCIT.PHONE = ENTRY_BLACKLIST.EMP_PHONE 
WHERE
	EHLOIT.ETP_ID = 'C2311231147301838934081353555974' 
	AND EHLOIT.STATUS = '1' 
	AND EHLOIT.DIMISSION_DATE IS NOT NULL 
ORDER BY
	EHLOIT.DIMISSION_DATE DESC,
	EHLOIT.LAST_MODI_TIME DESC,
	EHLOIT.CREATE_TIME DESC;

SELECT
ENTRY_BLACKLIST.ID,
ENTRY_BLACKLIST.EMP_PHONE,
	EHLOIT.ID AS EMP_NO,
	EHLOIT.EMP_NAME AS NAME,
	EHLOIT.PHONE AS MOBILE,
	EHLOIT.DEPART_ID AS DEP_ID,
	EEDIT.DEP_NAME,
	EHLOIT.JOB_TITILE,
	TCIT.ENTRY_TIME AS ENTRY_DATE,
CASE
	SUBSTRING( TCIT.EMP_NO, 1, 2 ) 
	WHEN 'WW' THEN
	'企微' 
	WHEN 'dt' THEN
	'钉钉' 
	WHEN 'fs' THEN
	'飞书' ELSE
CASE
	SUBSTRING( TCIT.EMP_NO, 1, 3 ) 
	WHEN 'QWD' THEN
	'企微' 
	WHEN 'kfp' THEN
	'泛微' 
	WHEN 'dyr' THEN
	'DBOX' ELSE '' 
END 
	END AS CHANNEL,
	EHWIT.REGULAR_WORKER_DATE,
	EHWIT.EMP_TYPE,
	EHABIT.ID_NUMBER,
	EHLOIT.DIMISSION_DATE,
	EHLOIT.REASONS_LEAVING,
	EHLOIT.REASONS_LEAVING_1,
	EHLOIT.REASONS_LEAVING_2,
	EHLOIT.NOTE,
	EHLOIT.JOB_NO,
CASE
	WHEN TRIM( ENTRY_BLACKLIST.EMP_PHONE ) IS NULL 
	OR TRIM( ENTRY_BLACKLIST.EMP_PHONE ) = '' THEN
	'1' ELSE '0' 
	END AS IS_BLACK 
FROM
	fuyao_user_dev.ENT_HR_LEAVE_OFFICE_INFO_TD EHLOIT
	LEFT JOIN fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT ON EHLOIT.ID = EHWIT.EMP_NO
	LEFT JOIN fuyao_user_dev.ENT_HR_ARCHIVE_BASIC_INFO_TD EHABIT ON EHLOIT.ID = EHABIT.EMP_NO
	LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD TCIT ON EHLOIT.ID = TCIT.EMP_ID
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT ON EEDIT.ETP_ID = EHLOIT.ETP_ID 
	AND EEDIT.DEP_ID = EHLOIT.DEPART_ID
	LEFT JOIN fuyao_user_dev.ENT_ENTRY_BLACKLIST_TD ENTRY_BLACKLIST ON EHLOIT.ETP_ID = ENTRY_BLACKLIST.ETP_ID 
	AND EHLOIT.PHONE = ENTRY_BLACKLIST.EMP_PHONE 
WHERE
	EHLOIT.ETP_ID = 'C2311231147301838934081353555974' 
	AND EHLOIT.STATUS = '1' 
ORDER BY
	EHLOIT.DIMISSION_DATE DESC,
	EHLOIT.LAST_MODI_TIME DESC,
	EHLOIT.CREATE_TIME DESC;

SELECT
EHCMT.EMP_NO,
	EHCMT.*,
	ECET.NAME,
	ECET.PHONE 
FROM
	fuyao_user_dev.ENT_HR_CONTRACT_MANAGE_TH EHCMT
	LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD ECET ON EHCMT.EMP_NO = ECET.EMP_ID
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT ON EEDIT.DEP_ID = ECET.DEP_ID 
	AND EEDIT.ETP_ID = ECET.ETP_ID 
	AND EEDIT.DEP_STATUS = '0' 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974'

S0ELECT
EHPAAT.DEPARTMENT,
EHPAAT.EXPECT_DEPARTMENT,
	EHPAAT.EMP_NAME AS NAME,
	ECET.ENTRY_TIME,
	EHPAAT.POST_ADJUST_DATE,
	EEDIT1.DEP_NAME AS DEPARTMENT,
	EEDIT2.DEP_NAME AS EXPECT_DEPARTMENT,
	EHPAAT.POST_RANK,
	EHPAAT.EXPECT_POST_RANK 
FROM
	fuyao_user_dev.ENT_HR_POST_ADJUST_APPL_TH EHPAAT
	LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD ECET ON EHPAAT.EMP_NO = ECET.EMP_ID
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT1 ON EEDIT1.DEP_ID = EHPAAT.DEPARTMENT 
	AND EEDIT1.ETP_ID = ECET.ETP_ID 
	AND EEDIT1.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT2 ON EEDIT2.DEP_ID = EHPAAT.EXPECT_DEPARTMENT 
	AND EEDIT2.ETP_ID = ECET.ETP_ID 
	AND EEDIT2.DEP_STATUS = '0' 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974' 
	AND (EHPAAT.DEPARTMENT = 'D2311231951231839055852723511301' or EHPAAT.EXPECT_DEPARTMENT = 'D2311231951231839055852723511301');

SELECT
	EHPAAT.DEPARTMENT,
	EHPAAT.EXPECT_DEPARTMENT,
	EHPAAT.POST_ADJUST_DATE AS LAST_MODI_TIME 
FROM
	fuyao_user_dev.ENT_HR_POST_ADJUST_APPL_TH EHPAAT
	left JOIN fuyao_user_dev.T_CUSTOM_INFO_TD ECET ON EHPAAT.EMP_NO = ECET.EMP_ID 
	
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT1 ON EEDIT1.DEP_ID = EHPAAT.DEPARTMENT 
	AND EEDIT1.ETP_ID = ECET.ETP_ID 
	AND EEDIT1.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT2 ON EEDIT2.DEP_ID = EHPAAT.EXPECT_DEPARTMENT 
	AND EEDIT2.ETP_ID = ECET.ETP_ID 
	AND EEDIT2.DEP_STATUS = '0'
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974';

SELECT
CASE
	
WHEN
	EHWIT.EMP_TYPE IS NULL THEN
	'无类型' ELSE EHWIT.EMP_TYPE 
END AS EMP_TYPE,
	EHWIT.EMP_STATUS,
IF
	( ECET.DEP_ID = '' OR ECET.DEP_ID IS NULL, '9999', ECET.DEP_ID ) AS DEP_ID,
	ECET.ENTRY_TIME 
FROM
	fuyao_user_dev.T_CUSTOM_INFO_TD ECET
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT ON EEDIT.ETP_ID = ECET.ETP_ID 
	AND EEDIT.DEP_ID = ECET.DEP_ID 
	AND EEDIT.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT ON ECET.EMP_ID = EHWIT.EMP_NO 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974' 
	AND ECET.VALID != 'I' 
	AND EEDIT.DEP_PATH LIKE CONCAT(
	'%','D2311231952171839056079731826694',
'%')

	SELECT
	GROUP_ID,
	FIELD_ID,
	ETP_ID,
	FIELD_NAME,
	IS_EXTEND_FIELD,
	IS_STOP_FIELD,
	IS_STOP_USING,
	IS_DELETE,
	FIELD_TYPE,
	IS_REQUIRED,
	SORT,
	EXTEND_FIELD,
	IS_EDIT,
	FIELD_LENGTH,
	EXTEND_FIELD_TYPE,
	TOOLTIP,
	IS_APPR_SHOW,
	CREATE_TIME,
	LAST_MODI_TIME 
FROM
	fuyao_user_dev.ENT_HR_DEP_FIELD_TD 
WHERE
	ETP_ID = '1' 
ORDER BY
	GROUP_ID,
	SORT ASC;


SELECT
	TT.* 
FROM
	(
SELECT
	ECET.EMP_ID EMP_NO,
	ECET.NAME,
	EEDIT.DEP_NAME,
	'宁波银行wuc
	个人测试公司' AS ETP_NAME,
CASE
	
	WHEN ( ECET.DEP_ID = '' OR ECET.DEP_ID IS NULL ) THEN
	'宁波银行wuc个人测试公司' ELSE EEDIT.DEP_NAME 
	END AS DEP_ID,
	ECET.DEP_ID DEPARTMENT,
	ECET.JOB_NO,
	ECET.JOB_TITILE,
	ECET.PHONE,
	EHWIT.EMP_TYPE,
	EHWIT.EMP_STATUS,
	ECET.ENTRY_TIME,
	ECET.ENTRY_LOCATION,
	ECET.JOB_TYPE,
	EHCMT.CONTRACT_COMPANY,
	EHCMT.CONTRACT_TYPE,
	EHCMT.CONTRACT_NO,
	EHCMT.FIRST_CONTRACT_SDATE,
	EHCMT.FIRST_CONTRACT_EDATE,
	EHCMT.CONTRACT_SDATE,
	EHCMT.CONTRACT_EDATE,
	EHCMT.CONTRACT_TIME_L IMIT,
	EHCMT.RENEWALS_NUM,
	EHABIT.ID_NAME,
	EHABIT.ID_NUMBER,
	EHABIT.BIRTHDAY,
	EHABIT.SOCIAL_SECURITY_BREAK_OFF,
IF
	( EHABIT.SOCIAL_SECURITY_BREAK_OFF = '' OR EHABIT.SOCIAL_SECURITY_BREAK_OFF IS NULL, '0', EHABIT.SOCIAL_SECURITY_BREAK_OFF ) AS SOCIAL_SECURITY_BREAK_OFF_ORDER,
IF
	( EHABIT.BIRTHDAY IS NULL, '', TIMESTAMPDIFF( YEAR, EHABIT.BIRTHDAY, DATE_FORMAT( NOW( ), '%Y-%m-%d' ) ) ) AS AGE,
	EHABIT.GENDER,
	EHABIT.NATIONAL,
	EHABIT.ID_CARD_ADDRESS,
	EHABIT.ID_CARD_VALIDITY,
	EHABIT.MARITAL_STATUS,
	EHABIT.FIRST_WORK_DATE,
	EHABIT.CENSUS_REG_TYPE,
	EHABIT.ADDRESS,
	EHABIT.POLITIC,
	EHABIT.SOCIAL_SECURITY_NO,
	EHABIT.ACCUMULATION_FUND_NO,
	EHABIT.BANK_NUMBER,
	EHA BIT.BANK_NAME,
	EHABIT.CLEARING_BANK,
	EHABIT.EXTENSION_NUMBER,
	EHABIT.OFFICE_LOCATION,
	EHABIT.E_MAIL,
	EHABIT.RELAT_POS_WORK_YEAR,
CASE
	EHABIT.ID_TYPE 
	WHEN '0' THE N '居民身份证' 
	WHEN '1' THEN
	'中国护照' 
	WHEN '2' THEN
	'港澳居民来往内地通行证' 
	WHEN '3' THEN
	'港澳居民居住证' 
	WHEN '4' THEN
	'台湾居民来往大陆通行证' 
	WHEN '5' THE N '台湾居民居住证' 
	WHEN '6' THEN
	'外国护照' 
	WHEN '7' THEN
	'外国人永久居留身份证' 
	WHEN '8' THEN
	'外国人工作许可证(A类)' 
	WHEN '9' THEN
	'外国人工作许可证(B类)' 
	WHEN '10' THEN
	'外国人工作许可证(C类)' ELSE '其他' 
	END AS ID_TYPE,
	EHWIT.PROBATION,
	EHWIT.REGULAR_WORKER_DATE,
	EHWIT.POST_RANK,
	CONCAT( COALESCE ( EERIT.RANK_CODE, '' ), COALESCE ( EERIT.RANK_NAME, '' ) ) POSITIONS,
	EHWIT.NOTE,
	EHWIT.PRE_WORKER_DATE,
	EHWIT.EMP_DOSSIER_NO,
	EHPMT.STAFF_PHOTOS,
	EHPMT.CONTRACT_ANNEX,
	ECET.CREATE_TIME,
	CON CAT ( ECET1.NAME, '|', ECET.SUPERVISOR ) SUPERVISOR 
FROM
	( SELECT * FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE ETP_ID = 'C2311231147301838934081353555974' AND VALID != 'I' ) ECET
	LEFT JOIN fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT ON ECET.EMP_ID = EHWIT.EMP_NO
	LEFT JOIN fuyao_user_dev.ENT_ETP_RANK_INFO_TD EERIT ON EHWIT.POSIT IONS = EERIT.RANK_ID
	LEFT JOIN fuyao_user_dev.ENT_HR_CONTRACT_MANAGE_TD EHCMT ON ECET.EMP_ID = EHCMT.EMP_NO
	LEFT JOIN fuyao_user_dev.ENT_HR_ARCHIVE_BASIC_INFO_TD EHABIT ON ECET.EMP_ID = EHABIT.EMP_NO
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT ON ECET.DEP_ID = EEDIT.DEP_ID 
	AND ECET.ETP_ID = EEDIT.ETP_ID 
	AND EEDIT.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD ECET1 ON ECET.ETP_ID = ECET1.ETP_ID 
	AND ECET.SUPERVISOR = ECET1.EMP_NO 
	AND ECET1.VALID != 'I' LEFT JO IN fuyao_user_dev.ENT_HR_PERSONAL_MATERIALS_TD EHPMT ON ECET.EMP_ID = EHPMT.EMP_NO 
	) TT 
ORDER BY
	TT.ENTRY_TIME,
	TT.CREATE_TIME DESC;


SELECT
	EMP_NO 
	,ETP_ID
FROM
	fuyao_user_dev.T_CUSTOM_INFO_TD 
WHERE
-- 	ETP_ID = 'C2302270910551741412341091209217' 
-- 	AND 
	EMP_ID = 'CS2402030104561864864298453315592' 
	AND VALID != 'I' 
	LIMIT 1

SELECT
ECET.VALID,
CASE
	
WHEN
	EHWIT.EMP_TYPE IS NULL THEN
	'无类型' ELSE EHWIT.EMP_TYPE 
	END AS EMP_TYPE,
	EEDIT.DEP_ID,
	EEDIT.DEP_NAME,
	EHLOIT.EMP_NAME AS NAME,
	EHWIT.POSITIONS,
	EHLOIT.PHONE,
	EHWIT.POST_RANK,
	EHLOIT.JOB_TITILE,
	EHLOIT.JOB_NO,
CASE
	EHWIT.EMP_STATUS 
	WHEN '0' THEN
	'试用' 
	WHEN '1' THEN
	'正式' 
	WHEN '2' THEN
	'待离职' 
	WHEN '3' THEN
	'已离职' ELSE '未知' 
	END AS EMP_STATUS,
	ECET.ENTRY_TIME,
	EHLOIT.DIMISSION_DATE,
	EHLOIT.STATUS,
	EHLOIT.EXPECT_DIMISSION_DATE,
	EHLOIT.REASONS_LEAVING,
	EHLOIT.REASONS_LEAVING_1,
	EHLOIT.REASONS_LEAVING_2 
FROM
	fuyao_user_dev.T_CUSTOM_INFO_TD ECET
	LEFT JOIN fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT ON ECET.EMP_ID = EHWIT.EMP_NO
	RIGHT JOIN fuyao_user_dev.ENT_HR_LEAVE_OFFICE_INFO_TD EHLOIT ON EHLOIT.ID = ECET.EMP_ID 
	AND EHLOIT.ETP_ID = ECET.ETP_ID
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT ON EEDIT.ETP_ID = ECET.ETP_ID 
	AND EEDIT.DEP_ID = ECET.DEP_ID 
	AND EEDIT.DEP_STATUS = '0' 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974' 
	AND ECET.VALID = 'I' 
	AND EEDIT.DEP_PATH LIKE CONCAT( '%/', CONCAT( 'D2311231951231839055852723511301', '%' ) ) 
	AND EHLOIT.EXPECT_DIMISSION_DATE >= '2024-01-01' 
	AND EHLOIT.EXPECT_DIMISSION_DATE <= '2024-12-31';

SELECT
CASE
	
WHEN
	EHWIT.EMP_TYPE IS NULL THEN
	'无类型' ELSE EHWIT.EMP_TYPE 
	END AS EMP_TYPE,
	EHWIT.EMP_STATUS,
IF
	( ECET.DEP_ID = '' OR ECET.DEP_ID IS NULL, '9999', ECET.DEP_ID ) AS DEP_ID,
	ECET.ENTRY_TIME 
FROM
	fuyao_user_dev.T_CUSTOM_INFO_TD ECET
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT ON EEDIT.ETP_ID = ECET.ETP_ID 
	AND EEDIT.DEP_ID = ECET.DEP_ID 
	AND EEDIT.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT ON ECET.EMP_ID = EHWIT.EMP_NO 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974' 
	AND ECET.VALID != 'I'
	order by ECET.ENTRY_TIME  desc;

SELECT
	EHPAAT.DEPARTMENT,
	EHPAAT.EXPECT_DEPARTMENT,
	EHPAAT.POST_ADJUST_DATE AS LAST_MODI_TIME 
FROM
	fuyao_user_dev.ENT_HR_POST_ADJUST_APPL_TH EHPAAT
	LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD ECET ON EHPAAT.EMP_NO = ECET.EMP_ID
	LEFT JOIN fuyao_user_dev.ENT_HR_ARCHIVE_BASIC_INFO_TD EHABI ON ECET.EMP_ID = EHABI.EMP_NO 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974' 
-- 	AND ECET.VALID != 'I' 
	AND EHABI.GENDER = '男'
	order by EHPAAT.POST_ADJUST_DATE desc;

SELECT
ECET.VALID,
EHABI.GENDER,
	EHLOIT.DIMISSION_DATE,
	EHLOIT.STATUS,
	EHLOIT.EMP_STATUS,
	EHLOIT.EXPECT_DIMISSION_DATE 
FROM
	fuyao_user_dev.ENT_HR_LEAVE_OFFICE_INFO_TD EHLOIT
	INNER JOIN ( SELECT CUSTOM_ID, MAX( LAST_MODI_TIME ) LAST_MODI_TIME FROM fuyao_user_dev.ENT_HR_LEAVE_OFFICE_INFO_TD WHERE ETP_ID = 'C2302270910551741412341091209217' GROUP BY CUSTOM_ID ) A ON EHLOIT.CUSTOM_ID = A.CUSTOM_ID 
	AND EHLOIT.LAST_MODI_TIME = A.LAST_MODI_TIME
	LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD ECET ON EHLOIT.ID = ECET.EMP_ID 
	AND EHLOIT.ETP_ID = ECET.ETP_ID
	LEFT JOIN fuyao_user_dev.ENT_ENTRY_CHANGE_TH EECT ON ECET.EMP_NO = EECT.EMP_NO
	LEFT JOIN fuyao_user_dev.ENT_HR_ARCHIVE_BASIC_INFO_TD EHABI ON ECET.EMP_ID = EHABI.EMP_NO 
WHERE
	EHLOIT.ETP_ID = 'C2302270910551741412341091209217' 
-- 	AND ECET.VALID != 'I' 
	AND EHABI.GENDER = '男';


update ENT_HR_POST_ADJUST_APPL_TH set POST_RANK = '1221' where EMP_NO= 'CS2401081846071855709270952570882';

SELECT
	* 
FROM
	(
SELECT
	CAST( c.num AS CHAR ) AS TOTAL_NUM,
	tt.* 
FROM
	(
SELECT
	@rownum := @rownum + 1 AS rn,
	t.* 
FROM
	(
SELECT
	EHPAAT.EMP_NO,
	EHPAAT.EMP_NAME,
	EHPAAT.EMP_PHONE,
	EHPAAT.JOB_NO,
	EHPAAT.DEPARTMENT,
	EHPAAT.JOB_TITILE,
	EHPAAT.POST_RANK,
	EHPAAT.POSITIONS,
	EHPAAT.EXPECT_DEPARTMENT,
	EHPAAT.EXPECT_JOB_TITILE,
	EHPAAT.EXPECT_POST_RANK,
	EHPAAT.EXPECT_POSITIONS,
	EHPAAT.POST_ADJUST_DATE,
	EHPAAT.REASON,
	EHPAAT.CREATE_TIME,
	EHPAAT.LAST_MODI_TIME,
	EHPAAT.PROCESS_INSTANCE_ID,
	EEDIT1.DEP_NAME AS DEPARTMENT_TXT,
	EEDIT2.DEP_NAME AS EXPECT_DEPARTMENT_TXT 
FROM
	fuyao_user_dev.T_CUSTOM_INFO_TD ECET
	INNER JOIN fuyao_user_dev.ENT_HR_POST_ADJUST_APPL_TH EHPAAT ON EHPAAT.EMP_NO = ECET.EMP_ID
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT1 ON EEDIT1.DEP_ID = EHPAAT.DEPARTMENT 
	AND EEDIT1.ETP_ID = 'C2311231147301838934081353555974' 
	AND EEDIT1.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT2 ON EEDIT2.DEP_ID = EHPAAT.EXPECT_DEPARTMENT 
	AND EEDIT2.ETP_ID = 'C2311231147301838934081353555974' 
	AND EEDIT2.DEP_STATUS = '0' 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974' 
	AND ECET.VALID != 'I' 
ORDER BY
	EHPAAT.POST_ADJUST_DATE ASC,
	EHPAAT.LAST_MODI_TIME DESC,
	EHPAAT.CREATE_TIME DESC 
	) t 
	) tt,
	( SELECT @rownum := 0 ) k,
	(
SELECT
	count( 1 ) num 
FROM
	(
SELECT
	EHPAAT.EMP_NO,
	EHPAAT.EMP_NAME,
	EHPAAT.EMP_PHONE,
	EHPAAT.JOB_NO,
	EHPAAT.DEPARTMENT,
	EHPAAT.JOB_TITILE,
	EHPAAT.POST_RANK,
	EHPAAT.POSITIONS,
	EHPAAT.EXPECT_DEPARTMENT,
	EHPAAT.EXPECT_JOB_TITILE,
	EHPAAT.EXPECT_POST_RANK,
	EHPAAT.EXPECT_POSITIONS,
	EHPAAT.POST_ADJUST_DATE,
	EHPAAT.REASON,
	EHPAAT.CREATE_TIME,
	EHPAAT.LAST_MODI_TIME,
	EHPAAT.PROCESS_INSTANCE_ID,
	EEDIT1.DEP_NAME AS DEPARTMENT_TXT,
	EEDIT2.DEP_NAME AS EXPECT_DEPARTMENT_TXT 
FROM
	fuyao_user_dev.T_CUSTOM_INFO_TD ECET
	INNER JOIN fuyao_user_dev.ENT_HR_POST_ADJUST_APPL_TH EHPAAT ON EHPAAT.EMP_NO = ECET.EMP_ID
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT1 ON EEDIT1.DEP_ID = EHPAAT.DEPARTMENT 
	AND EEDIT1.ETP_ID = 'C2311231147301838934081353555974' 
	AND EEDIT1.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT2 ON EEDIT2.DEP_ID = EHPAAT.EXPECT_DEPARTMENT 
	AND EEDIT2.ETP_ID = 'C2311231147301838934081353555974' 
	AND EEDIT2.DEP_STATUS = '0' 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974' 
	AND ECET.VALID != 'I' 
ORDER BY
	EHPAAT.POST_ADJUST_DATE ASC,
	EHPAAT.LAST_MODI_TIME DESC,
	EHPAAT.CREATE_TIME DESC 
	) rw 
	) c 
	) row_ 
WHERE
	row_.rn <= 11;


select T1.* from T_BESTSIGN_CONTRACT_INFO_TD T1
order by T1.CONTRACT_STATUS,T1.CREATE_TIME;



SELECT EMP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE ETP_ID = 'C2205121337041636024447668297731' AND EMP_NO = 'S2111241629321574824300668280833' AND VALID != 'I';

INSERT INTO `fuyao_user_dev`.`T_CUSTOM_INFO_TD`(`EMP_ID`, `ETP_ID`, `DEP_ID`, `PRJ_ID`, `CUSTOM_ID`, `PHONE`, `ACCUMULATION_FUND_NO`, `SOCIAL_SECURITY_NO`, `BANK_NUMBER`, `NAME`, `BEREGULAR_TIME`, `RESI_TIME`, `ENTRY_TIME`, `ENTRY_LOCATION`, `ID_NO`, `POLITIC`, `ADDRESS`, `CENSUS_REG_TYPE`, `FIRST_WORK_DATE`, `MARITAL_STATUS`, `ID_CARD_VALIDITY`, `ID_CARD_ADDRESS`, `NATIONAL`, `GENDER`, `BIRTHDAY`, `VALID`, `BANK_NAME`, `OFFICE_LOCATION`, `E_MAIL`, `CUSTOM_ROLE`, `CUSTOM_TYPE`, `JOB_NO`, `EXTENSION_NUMBER`, `JOB_TITILE`, `CREATE_TIME`, `UPT_TIME`, `SALARY_GROUP_ID`, `CUST_AVATAR_PATH`, `EMP_NO`, `CLEARING_BANK`, `ID_NAME`, `POST_RANK`, `PROBATION`, `CONTRACT_COMPANY`, `CONTRACT_TYPE`, `JOB_TYPE`, `SUPERVISOR`, `E_SIGNATURE`, `FORBIDDEN`) VALUES ('94e3ca4035654125851a4a88920c4f00', 'C2205121337041636024447668297731', '', '', 'c2312130950461846152460644339713', '15155953211', '9', '9', '', '钟楠', '', NULL, '2022-01-01', '', NULL, NULL, NULL, '', '', NULL, NULL, NULL, NULL, '0', '', 'A', '', '', NULL, 'P', 'QZ', '', NULL, '', '2024-01-24 09:38:06', '2024-01-24 09:38:06', NULL, '', 'S2401240938001861369538902986009', '', '', '', '', '', '', NULL, '', NULL, '0');


SELECT
	EHFFTIT.TEMPL_FIELD 
FROM
	fuyao_user_dev.ENT_HR_ORG_FIELD_TEMPL_INFO_TD EHFFTIT
	LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD TCIT ON EHFFTIT.EMP_ID = TCIT.EMP_ID 
	AND EHFFTIT.ETP_ID = TCIT.ETP_ID 
	AND TCIT.VALID != 'I' 
WHERE
	EHFFTIT.ETP_ID = 'C2205121337041636024447668297731' 
	AND TCIT.EMP_NO = 'S2111241629321574824300668280833';



SELECT
	EHPAAT.DEPARTMENT,
	EHPAAT.EXPECT_DEPARTMENT,
	EHPAAT.POST_ADJUST_DATE AS LAST_MODI_TIME 
FROM
	fuyao_user_dev.ENT_HR_POST_ADJUST_APPL_TH EHPAAT
	LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD ECET ON EHPAAT.EMP_NO = ECET.EMP_ID 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974'
	order by EHPAAT.POST_ADJUST_DATE


select
			distinct EHCMT.CONTRACT_COMPANY
		from ENT_HR_CONTRACT_MANAGE_TD EHCMT
		inner join
			 T_CUSTOM_INFO_TD CUSTOM_INFO on CUSTOM_INFO.EMP_ID = EHCMT.EMP_NO
		where CUSTOM_INFO.ETP_ID = 'C2211231636271706735227059494912';


		SELECT
	EXTEND_FIELD,
	FIELD_NAME,
	IS_EXTEND_FIELD,
	FIELD_ID,
	GROUP_ID,
	CITE_DOSSIER_FIELD,
	CITE_DOSSIER_FIELD_NAME 
FROM
	fuyao_user_dev.ENT_HR_DOSSIER_FIELD_TD 
WHERE
	FIELD_TYPE = '2' 
	AND GROUP_ID = 'ENT_CUST_ENTERPRISE_TM' 
	AND FIELD_ID = 'JOB_TITILE' 
	AND ETP_ID = 'C2302270910551741412341091209217';

SELECT DISTINCT
	EHRT.*,
	EHDFT.FIELD_NAME 
FROM
	fuyao_user_dev.ENT_HR_REPORT_TD EHRT
	LEFT JOIN fuyao_user_dev.ENT_HR_DOSSIER_FIELD_TD EHDFT ON EHDFT.FIELD_ID = EHRT.FIELD_TYPE 
	AND EHRT.ETP_ID = EHDFT.ETP_ID 
WHERE
	EHRT.ETP_ID = 'C2302270910551741412341091209217';


SELECT
	EHPAAT.EMP_NO,
	EHPAAT.EMP_NAME,
	EHPAAT.EMP_PHONE,
	EHPAAT.JOB_NO,
	EHPAAT.DEPARTMENT,
	EHPAAT.JOB_TITILE POST_RANK,
	EHPAAT.EXPECT_DEPARTMENT,
	EHPAAT.EXPECT_JOB_TITILE EXPECT_POST_RANK,
	CONCAT( RANK_INF.RANK_CODE, RANK_INF.RANK_NAME ) AS EXPECT_POSITIONS,
	EHPAAT.POSITIONS,
	EHPAAT.POST_ADJUST_DATE,
	EHPAAT.REASON,
	EHPAAT.CREATE_TIME,
	EHPAAT.LAST_MODI_TIME,
	EHPAAT.PROCESS_INSTANCE_ID,
	EHPAAT.PROJECT JOB_TITILE,
	EHPAAT.EXPECT_PROJECT EXPECT_JOB_TITILE,
	EHPAAT.FIX_LIST,
	EEDIT1.DEP_NAME AS DEPARTMENT_TXT,
	EEDIT2.DEP_NAME AS EXPECT_DEPARTMENT_TXT 
FROM
	fuyao_user_dev.T_CUSTOM_INFO_TD ECET
	INNER JOIN fuyao_user_dev.ENT_HR_POST_ADJUST_APPL_TD EHPAAT ON EHPAAT.EMP_NO = ECET.EMP_ID
	LEFT JOIN fuyao_user_dev.ENT_ETP_RANK_INFO_TD RANK_INF ON RANK_INF.RANK_ID = EHPAAT.EXPECT_POSITIONS
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT1 ON EEDIT1.DEP_ID = EHPAAT.DEPARTMENT 
	AND EEDIT1.ETP_ID = 'C2311231147301838934081353555974' 
	AND EEDIT1.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT2 ON EEDIT2.DEP_ID = EHPAAT.EXPECT_DEPARTMENT 
	AND EEDIT2.ETP_ID = 'C2311231147301838934081353555974' 
	AND EEDIT2.DEP_STATUS = '0' 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974' 
	AND ECET.VALID != 'I' 
ORDER BY
	EHPAAT.POST_ADJUST_DATE ASC,
	EHPAAT.LAST_MODI_TIME DESC,
	EHPAAT.CREATE_TIME DESC;

select name from T_CUSTOM_INFO_TD where EMP_NO = 'CS2311242253361839464099312066566';


SELECT
	* 
FROM
	(
SELECT
	CAST( c.num AS CHAR ) AS TOTAL_NUM,
	tt.* 
FROM
	(
SELECT
	@rownum := @rownum + 1 AS rn,
	t.* 
FROM
	(
SELECT
	EHPAAT.EMP_NO,
	EHPAAT.EMP_NAME,
	EHPAAT.EMP_PHONE,
	EHPAAT.JOB_NO,
	EHPAAT.DEPARTMENT,
	EHPAAT.JOB_TITILE,
	EHPAAT.POST_RANK,
	EHPAAT.POSITIONS,
	EHPAAT.EXPECT_DEPARTMENT,
	EHPAAT.EXPECT_JOB_TITILE,
	EHPAAT.EXPECT_POST_RANK,
	EHPAAT.EXPECT_POSITIONS,
	EHPAAT.POST_ADJUST_DATE,
	EHPAAT.REASON,
	EHPAAT.CREATE_TIME,
	EHPAAT.LAST_MODI_TIME,
	EHPAAT.PROCESS_INSTANCE_ID,
	EEDIT1.DEP_NAME AS DEPARTMENT_TXT,
	EEDIT2.DEP_NAME AS EXPECT_DEPARTMENT_TXT 
FROM
	fuyao_user_dev.T_CUSTOM_INFO_TD ECET
	INNER JOIN fuyao_user_dev.ENT_HR_POST_ADJUST_APPL_TH EHPAAT ON EHPAAT.EMP_NO = ECET.EMP_ID
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT1 ON EEDIT1.DEP_ID = EHPAAT.DEPARTMENT 
	AND EEDIT1.ETP_ID = 'C2311231147301838934081353555974' 
	AND EEDIT1.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT2 ON EEDIT2.DEP_ID = EHPAAT.EXPECT_DEPARTMENT 
	AND EEDIT2.ETP_ID = 'C2311231147301838934081353555974' 
	AND EEDIT2.DEP_STATUS = '0' 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974' 
	AND ECET.VALID != 'I' 
ORDER BY
	EHPAAT.POST_ADJUST_DATE ASC,
	EHPAAT.LAST_MODI_TIME DESC,
	EHPAAT.CREATE_TIME DESC 
	) t 
	) tt,
	( SELECT @rownum := 0 ) k,
	(
SELECT
	count( 1 ) num 
FROM
	(
SELECT
	EHPAAT.EMP_NO,
	EHPAAT.EMP_NAME,
	EHPAAT.EMP_PHONE,
	EHPAAT.JOB_NO,
	EHPAAT.DEPARTMENT,
	EHPAAT.JOB_TITILE,
	EHPAAT.POST_RANK,
	EHPAAT.POSITIONS,
	EHPAAT.EXPECT_DEPARTMENT,
	EHPAAT.EXPECT_JOB_TITILE,
	EHPAAT.EXPECT_POST_RANK,
	EHPAAT.EXPECT_POSITIONS,
	EHPAAT.POST_ADJUST_DATE,
	EHPAAT.REASON,
	EHPAAT.CREATE_TIME,
	EHPAAT.LAST_MODI_TIME,
	EHPAAT.PROCESS_INSTANCE_ID,
	EEDIT1.DEP_NAME AS DEPARTMENT_TXT,
	EEDIT2.DEP_NAME AS EXPECT_DEPARTMENT_TXT 
FROM
	fuyao_user_dev.T_CUSTOM_INFO_TD ECET
	INNER JOIN fuyao_user_dev.ENT_HR_POST_ADJUST_APPL_TH EHPAAT ON EHPAAT.EMP_NO = ECET.EMP_ID
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT1 ON EEDIT1.DEP_ID = EHPAAT.DEPARTMENT 
	AND EEDIT1.ETP_ID = 'C2311231147301838934081353555974' 
	AND EEDIT1.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT2 ON EEDIT2.DEP_ID = EHPAAT.EXPECT_DEPARTMENT 
	AND EEDIT2.ETP_ID = 'C2311231147301838934081353555974' 
	AND EEDIT2.DEP_STATUS = '0' 
WHERE
	ECET.ETP_ID = 'C2311231147301838934081353555974' 
	AND ECET.VALID != 'I' 
ORDER BY
	EHPAAT.POST_ADJUST_DATE ASC,
	EHPAAT.LAST_MODI_TIME DESC,
	EHPAAT.CREATE_TIME DESC 
	) rw 
	) c 
	) row_ 
WHERE
	row_.rn <= 11;



select dep.DEP_NAME,ext.FIELD_ID,ext.FIELD_VALUE from  ENT_HR_DEP_FIELD_EXTEND_TD ext join T_ETP_DEPART_INFO_TD dep on dep.dep_id = ext.OBJ_ID order by ext.CREATE_TIME limit 100;


SELECT TT.* FROM (SELECT ECET.EMP_ID EMP_NO, ECET.NAME, EEDIT.DEP_NAME, '宁波银行测试专用' AS ETP_NAME, CASE WHEN (ECET.DEP_ID = '' or ECET.DEP_ID is NULL) THEN '宁波银行测试专用' ELSE EEDIT.DEP_NAME END AS DEP_ID, ECET.DEP_ID DEPARTMENT, ECET.JOB_NO, ECET.JOB_TITILE, ECET.PHONE, EHWIT.EMP_TYPE, EHWIT.EMP_STATUS, ECET.ENTRY_TIME, ECET.ENTRY_LOCATION, ECET.JOB_TYPE, EHCMT.CONTRACT_COMPANY, EHCMT.CONTRACT_TYPE, EHCMT.CONTRACT_NO, EHCMT.FIRST_CONTRACT_SDATE, EHCMT.FIRST_CONTRACT_EDATE, EHCMT.CONTRACT_SDATE, EHCMT.CONTRACT_EDATE, EHCMT.CONTRACT_TIME_LIMIT, EHCMT.RENEWALS_NUM, EHABIT.ID_NAME, EHABIT.ID_NUMBER, EHABIT.BIRTHDAY, EHABIT.SOCIAL_SECURITY_BREAK_OFF, if(EHABIT.SOCIAL_SECURITY_BREAK_OFF = '' or EHABIT.SOCIAL_SECURITY_BREAK_OFF is null, '0', EHABIT.SOCIAL_SECURITY_BREAK_OFF) AS SOCIAL_SECURITY_BREAK_OFF_ORDER, IF(EHABIT.BIRTHDAY IS NULL, '',TIMESTAMPDIFF(YEAR, EHABIT.BIRTHDAY, DATE_FORMAT(NOW(), '%Y-%m-%d'))) AS AGE, EHABIT.GENDER, EHABIT.NATIONAL, EHABIT.ID_CARD_ADDRESS, EHABIT.ID_CARD_VALIDITY, EHABIT.MARITAL_STATUS, EHABIT.FIRST_WORK_DATE, EHABIT.CENSUS_REG_TYPE, EHABIT.ADDRESS, EHABIT.POLITIC, EHABIT.SOCIAL_SECURITY_NO, EHABIT.ACCUMULATION_FUND_NO, EHABIT.BANK_NUMBER, EHABIT.BANK_NAME, EHABIT.CLEARING_BANK, EHABIT.EXTENSION_NUMBER, EHABIT.OFFICE_LOCATION, EHABIT.E_MAIL, EHABIT.RELAT_POS_WORK_YEAR, CASE EHABIT.ID_TYPE WHEN '0' THEN '居民身份证' WHEN '1' THEN '中国护照' WHEN '2' THEN '港澳居民来往内地通行证' WHEN '3' THEN '港澳居民居住证' WHEN '4' THEN '台湾居民
来往大陆通行证' WHEN '5' THEN '台湾居民居住证' WHEN '6' THEN '外国护照' WHEN '7' THEN '外国人永久居留身份证' WHEN '8' THEN '外国人工作许可证(A类)' WHEN '9' THEN '外国人工作许可证(B类)' WHEN '10' THEN '外国人工作许可证(C类)' ELSE '其他' END AS ID_TYPE, EHWIT.PROBATION, EHWIT.REGULAR_WORKER_DATE, EHWIT.POST_RANK, CASE '0' WHEN '0' THEN CONCAT( COALESCE ( EERIT.RANK_CODE, '' ), COALESCE ( EERIT.RANK_NAME, '' ) ) WHEN '1' THEN EERIT.RANK_CODE WHEN '2' THEN EERIT.RANK_NAME ELSE CONCAT(COALESCE ( EERIT.RANK_CODE, '' ), COALESCE ( EERIT.RANK_NAME, '' )) END AS POSITIONS, EHWIT.NOTE, EHWIT.PRE_WORKER_DATE, IF(EHWIT.PRE_WORKER_DATE IS NULL, '', DATE_ADD(EHWIT.PRE_WORKER_DATE, INTERVAL -1 DAY)) PRE_WORKER_FRONT_DATE, EHWIT.EMP_DOSSIER_NO, EHPMT.STAFF_PHOTOS, EHPMT.CONTRACT_ANNEX, ECET.CREATE_TIME, CONCAT(ECET1.NAME,'|', ECET.SUPERVISOR) SUPERVISOR FROM ( SELECT * FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE ETP_ID = 'C2302270910551741412341091209217' AND VALID != 'I' ) ECET LEFT JOIN fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT ON ECET.EMP_ID = EHWIT.EMP_NO LEFT JOIN fuyao_user_dev.ENT_ETP_RANK_INFO_TD EERIT ON EHWIT.POSITIONS = EERIT.RANK_ID LEFT JOIN fuyao_user_dev.ENT_HR_CONTRACT_MANAGE_TD EHCMT ON ECET.EMP_ID = EHCMT.EMP_NO LEFT JOIN fuyao_user_dev.ENT_HR_ARCHIVE_BASIC_INFO_TD EHABIT ON ECET.EMP_ID = EHABIT.EMP_NO LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT ON ECET.DEP_ID = EEDIT.DEP_ID AND ECET.ETP_ID = EEDIT.ETP_ID AND EEDIT.DEP_STATUS = '0' LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD ECET1 ON ECET.ETP_ID = ECET1.ETP_ID AND ECET.SUPERVISOR = ECET1.EMP_NO AND ECET1.VALID != 'I' LEFT JOIN fuyao_user_dev.ENT_HR_PERSONAL_MATERIALS_TD EHPMT ON ECET.EMP_ID = EHPMT.EMP_NO ) TT ORDER BY TT.ENTRY_TIME, TT.CREATE_TIME DESC;


update ENT_HR_DOSSIER_FIELD_TD set FLOW_SHOW_TYPE = null;
select * from ENT_HR_DOSSIER_FIELD_TD where  FLOW_SHOW_TYPE != null;


SELECT
	EHWIT.EMP_NO,
	EHWIT.EMP_TYPE,
	EHWIT.EMP_STATUS,
	EHWIT.PROBATION,
	EHWIT.PRE_WORKER_DATE,
	EHWIT.REGULAR_WORKER_DATE,
	EHWIT.POST_RANK,
	EHWIT.EMP_DOSSIER_NO,
	EHWIT.NOTE,
	EHWIT.CREATE_TIME,
	EHWIT.LAST_MODI_TIME,
CASE
	'0' 
	WHEN '0' THEN
	CONCAT( ETRIT.RANK_CODE, ' ', IFNULL( ETRIT.RANK_NAME, '' ) ) 
	WHEN '1' THEN
	ETRIT.RANK_CODE 
	WHEN '2' THEN
	IFNULL( ETRIT.RANK_NAME, '' ) ELSE CONCAT( ETRIT.RANK_CODE, ' ', IFNULL( ETRIT.RANK_NAME, '' ) ) 
	END AS POSITIONS,
IF
	(
	EHWIT.POSITIONS != NULL 
	OR EHWIT.POSITIONS != '',							
	CONCAT( ETRIT.RANK_NAME, '|', ETRIT.RANK_ID ),
NULL 
	) AS POSITIONS_APPR 
FROM
	fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT
	LEFT JOIN fuyao_user_dev.ENT_ETP_RANK_INFO_TD ETRIT ON EHWIT.POSITIONS = ETRIT.RANK_ID 
WHERE
	EHWIT.EMP_NO = 'CS2311242253361839464099312066566';

SELECT
	* 
FROM
	(
SELECT
	CAST( c.num AS CHAR ) AS TOTAL_NUM,
	tt.* 
FROM
	(
SELECT
	@rownum := @rownum + 1 AS rn,
	t.* 
FROM
	(
SELECT
	TT.* 
FROM
	(
SELECT
	ECET.EMP_ID EMP_NO,
	ECET.NAME,
	EEDIT.DEP_NAME,
	'宁波银行wuc个人测试公司' AS ETP_NAME,
CASE
	
	WHEN ( ECET.DEP_ID = '' OR ECET.DEP_ID IS NULL ) THEN
	'宁波银行wuc个人测试公司' ELSE EEDIT.DEP_NAME 
	END AS DEP_ID,
	ECET.DEP_ID DEPARTMENT,
	ECET.JOB_NO,
	ECET.JOB_TITILE,
	ECET.PHONE,
	EHWIT.EMP_TYPE,
	EHWIT.EMP_STATUS,
	ECET.ENTRY_TIME,
	ECET.ENTRY_LOCATION,
	ECET.JOB_TYPE,
	EHCMT.CONTRACT_COMPANY,
	EHCMT.CONTRACT_TYPE,
	EHCMT.CONTRACT_NO,
	EHCMT.FIRST_CONTRACT_SDATE,
	EHCMT.FIRST_CONTRACT_EDATE,
	EHCMT.CONTRACT_SDATE,
	EHCMT.CONTRACT_EDATE,
	EHCMT.CONTRACT_TIME_LIMIT,
	EHCMT.RENEWALS_NUM,
	EHABIT.ID_NAME,
	EHABIT.ID_NUMBER,
	EHABIT.BIRTHDAY,
	EHABIT.SOCIAL_SECURITY_BREAK_OFF,
IF
	( EHABIT.SOCIAL_SECURITY_BREAK_OFF = '' OR EHABIT.SOCIAL_SECURITY_BREAK_OFF IS NULL, '0', EHABIT.SOCIAL_SECURITY_BREAK_OFF ) AS SOCIAL_SECURITY_BREAK_OFF_ORDER,
IF
	( EHABIT.BIRTHDAY IS NULL, '', TIMESTAMPDIFF( YEAR, EHABIT.BIRTHDAY, DATE_FORMAT( NOW( ), '%Y-%m-%d' ) ) ) AS AGE,
	EHABIT.GENDER,
	EHABIT.NATIONAL,
	EHABIT.ID_CARD_ADDRESS,
	EHABIT.ID_CARD_VALIDITY,
	EHABIT.MARITAL_STATUS,
	EHABIT.FIRST_WORK_DATE,
	EHABIT.CENSUS_REG_TYPE,
	EHABIT.ADDRESS,
	EHABIT.POLITIC,
	EHABIT.SOCIAL_SECURITY_NO,
	EHABIT.ACCUMULATION_FUND_NO,
	EHABIT.BANK_NUMBER,
	EHABIT.BANK_NAME,
	EHABIT.CLEARING_BANK,
	EHABIT.EXTENSION_NUMBER,
	EHABIT.OFFICE_LOCATION,
	EHABIT.E_MAIL,
	EHABIT.RELAT_POS_WORK_YEAR,
CASE
		EHABIT.ID_TYPE 
		WHEN '0' THEN
		'居民身份证' 
		WHEN '1' THEN
		'中国护照' 
		WHEN '2' THEN
		'港澳居民来往内地通行证' 
		WHEN '3' THEN
		'港澳居民居住证' 
		WHEN '4' THEN
		'台湾居民来往大陆通行证' 
		WHEN '5' THEN
		'台湾居民居住证' 
		WHEN '6' THEN
		'外国护照' 
		WHEN '7' THEN
		'外国人永久居留身份证' 
		WHEN '8' THEN
		'外国人工作许可证(A类)' 
		WHEN '9' THEN
		'外国人工作许可证(B类)' 
		WHEN '10' THEN
		'外国人工作许可证(C类)' ELSE '其他' 
	END AS ID_TYPE,
	EHWIT.PROBATION,
	EHWIT.REGULAR_WORKER_DATE,
	EHWIT.POST_RANK,
	CONCAT( COALESCE ( EERIT.RANK_CODE, '' ), COALESCE ( EERIT.RANK_NAME, '' ) ) POSITIONS,
	EHWIT.NOTE,
	EHWIT.PRE_WORKER_DATE,
IF
	( EHWIT.PRE_WORKER_DATE IS NULL, '', DATE_ADD( EHWIT.PRE_WORKER_DATE, INTERVAL - 1 DAY ) ) PRE_WORKER_FRONT_DATE,
	EHWIT.EMP_DOSSIER_NO,
	EHPMT.STAFF_PHOTOS,
	EHPMT.CONTRACT_ANNEX,
	ECET.CREATE_TIME,
	CONCAT( ECET1.NAME, '|', ECET.SUPERVISOR ) SUPERVISOR 
FROM
	( SELECT * FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE ETP_ID = 'C2311231147301838934081353555974' AND VALID != 'I' ) ECET
	LEFT JOIN fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT ON ECET.EMP_ID = EHWIT.EMP_NO
	LEFT JOIN fuyao_user_dev.ENT_ETP_RANK_INFO_TD EERIT ON EHWIT.POSITIONS = EERIT.RANK_ID
	LEFT JOIN fuyao_user_dev.ENT_HR_CONTRACT_MANAGE_TD EHCMT ON ECET.EMP_ID = EHCMT.EMP_NO
	LEFT JOIN fuyao_user_dev.ENT_HR_ARCHIVE_BASIC_INFO_TD EHABIT ON ECET.EMP_ID = EHABIT.EMP_NO
	LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT ON ECET.DEP_ID = EEDIT.DEP_ID 
	AND ECET.ETP_ID = EEDIT.ETP_ID 
	AND EEDIT.DEP_STATUS = '0'
	LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD ECET1 ON ECET.ETP_ID = ECET1.ETP_ID 
	AND ECET.SUPERVISOR = ECET1.EMP_NO 
	AND ECET1.VALID != 'I'
	LEFT JOIN fuyao_user_dev.ENT_HR_PERSONAL_MATERIALS_TD EHPMT ON ECET.EMP_ID = EHPMT.EMP_NO 
WHERE
	EHWIT.EMP_TYPE = '全职' 
	) TT 
ORDER BY
	TT.ENTRY_TIME,
	TT.CREATE_TIME DESC 
	) t 
	) tt,
	( SELECT @rownum := 0 ) k,
	(
	SELECT
		count( 1 ) num 
	FROM
		(
		SELECT
			TT.* 
		FROM
			(
			SELECT
				ECET.EMP_ID EMP_NO,
				ECET.NAME,
				EEDIT.DEP_NAME,
				'宁波银行wuc个人测试公司' AS ETP_NAME,
			CASE
					
					WHEN ( ECET.DEP_ID = '' OR ECET.DEP_ID IS NULL ) THEN
					'宁波银行wuc个人测试公司' ELSE EEDIT.DEP_NAME 
				END AS DEP_ID,
				ECET.DEP_ID DEPARTMENT,
				ECET.JOB_NO,
				ECET.JOB_TITILE,
				ECET.PHONE,
				EHWIT.EMP_TYPE,
				EHWIT.EMP_STATUS,
				ECET.ENTRY_TIME,
				ECET.ENTRY_LOCATION,
				ECET.JOB_TYPE,
				EHCMT.CONTRACT_COMPANY,
				EHCMT.CONTRACT_TYPE,
				EHCMT.CONTRACT_NO,
				EHCMT.FIRST_CONTRACT_SDATE,
				EHCMT.FIRST_CONTRACT_EDATE,
				EHCMT.CONTRACT_SDATE,
				EHCMT.CONTRACT_EDATE,
				EHCMT.CONTRACT_TIME_LIMIT,
				EHCMT.RENEWALS_NUM,
				EHABIT.ID_NAME,
				EHABIT.ID_NUMBER,
				EHABIT.BIRTHDAY,
				EHABIT.SOCIAL_SECURITY_BREAK_OFF,
			IF
				( EHABIT.SOCIAL_SECURITY_BREAK_OFF = '' OR EHABIT.SOCIAL_SECURITY_BREAK_OFF IS NULL, '0', EHABIT.SOCIAL_SECURITY_BREAK_OFF ) AS SOCIAL_SECURITY_BREAK_OFF_ORDER,
			IF
				( EHABIT.BIRTHDAY IS NULL, '', TIMESTAMPDIFF( YEAR, EHABIT.BIRTHDAY, DATE_FORMAT( NOW( ), '%Y-%m-%d' ) ) ) AS AGE,
				EHABIT.GENDER,
				EHABIT.NATIONAL,
				EHABIT.ID_CARD_ADDRESS,
				EHABIT.ID_CARD_VALIDITY,
				EHABIT.MARITAL_STATUS,
				EHABIT.FIRST_WORK_DATE,
				EHABIT.CENSUS_REG_TYPE,
				EHABIT.ADDRESS,
				EHABIT.POLITIC,
				EHABIT.SOCIAL_SECURITY_NO,
				EHABIT.ACCUMULATION_FUND_NO,
				EHABIT.BANK_NUMBER,
				EHABIT.BANK_NAME,
				EHABIT.CLEARING_BANK,
				EHABIT.EXTENSION_NUMBER,
				EHABIT.OFFICE_LOCATION,
				EHABIT.E_MAIL,
				EHABIT.RELAT_POS_WORK_YEAR,
			CASE
					EHABIT.ID_TYPE 
					WHEN '0' THEN
					'居民身份证' 
					WHEN '1' THEN
					'中国护照' 
					WHEN '2' THEN
					'港澳居民来往内地通行证' 
					WHEN '3' THEN
					'港澳居民居住证' 
					WHEN '4' THEN
					'台湾居民来往大陆通行证' 
					WHEN '5' THEN
					'台湾居民居住证' 
					WHEN '6' THEN
					'外国护照' 
					WHEN '7' THEN
					'外国人永久居留身份证' 
					WHEN '8' THEN
					'外国人工作许可证(A类)' 
					WHEN '9' THEN
					'外国人工作许可证(B类)' 
					WHEN '10' THEN
					'外国人工>作许可证(C类)' ELSE '其他' 
				END AS ID_TYPE,
				EHWIT.PROBATION,
				EHWIT.REGULAR_WORKER_DATE,
				EHWIT.POST_RANK,
				CONCAT( COALESCE ( EERIT.RANK_CODE, '' ), COALESCE ( EERIT.RANK_NAME, '' ) ) POSITIONS,
				EHWIT.NOTE,
				EHWIT.PRE_WORKER_DATE,
			IF
				( EHWIT.PRE_WORKER_DATE IS NULL, '', DATE_ADD( EHWIT.PRE_WORKER_DATE, INTERVAL - 1 DAY ) ) PRE_WORKER_FRONT_DATE,
				EHWIT.EMP_DOSSIER_NO,
				EHPMT.STAFF_PHOTOS,
				EHPMT.CONTRACT_ANNEX,
				ECET.CREATE_TIME,
				CONCAT( ECET1.NAME, '|', ECET.SUPERVISOR ) SUPERVISOR 
			FROM
				( SELECT * FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE ETP_ID = 'C2311231147301838934081353555974' AND VALID != 'I' ) ECET
				LEFT JOIN fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT ON ECET.EMP_ID = EHWIT.EMP_NO
				LEFT JOIN fuyao_user_dev.ENT_ETP_RANK_INFO_TD EERIT ON EHWIT.POSITIONS = EERIT.RANK_ID
				LEFT JOIN fuyao_user_dev.ENT_HR_CONTRACT_MANAGE_TD EHCMT ON ECET.EMP_ID = EHCMT.EMP_NO
				LEFT JOIN fuyao_user_dev.ENT_HR_ARCHIVE_BASIC_INFO_TD EHABIT ON ECET.EMP_ID = EHABIT.EMP_NO
				LEFT JOIN fuyao_user_dev.T_ETP_DEPART_INFO_TD EEDIT ON ECET.DEP_ID = EEDIT.DEP_ID 
				AND ECET.ETP_ID = EEDIT.ETP_ID 
				AND EEDIT.DEP_STATUS = '0'
				LEFT JOIN fuyao_user_dev.T_CUSTOM_INFO_TD ECET1 ON ECET.ETP_ID = ECET1.ETP_ID 
				AND ECET.SUPERVISOR = ECET1.EMP_NO 
				AND ECET1.VALID != 'I'
				LEFT JOIN fuyao_user_dev.ENT_HR_PERSONAL_MATERIALS_TD EHPMT ON ECET.EMP_ID = EHPMT.EMP_NO 
			WHERE
				EHWIT.EMP_TYPE = '全职' 
			) TT 
		ORDER BY
			TT.ENTRY_TIME,
			TT.CREATE_TIME DESC 
		) rw 
	) c 
	) row_ 
WHERE
row_.rn <= 11;



select * FROM fuyao_user_dev.T_CUSTOM_INFO_TD where NAME = '赵十' AND ETP_ID = 'C2311231147301838934081353555974' and VALID!='I';


SELECT
	COUNT( ECET.EMP_ID ) AS EMP_NUM,
	ECET.NAME,
	ECET.ENTRY_TIME,
	ECET.JOB_TITILE,
	ECET.JOB_NO,
	EHWIT.PROBATION 
FROM
	fuyao_user_dev.T_CUSTOM_INFO_TD ECET
	INNER JOIN fuyao_user_dev.ENT_HR_WORK_INFO_TD EHWIT ON EHWIT.EMP_NO = ECET.EMP_ID 
WHERE
	ECET.EMP_ID = 'CS2401181629411859298815375544320' 
	AND ECET.ETP_ID = 'C2311231147301838934081353555974' 
	AND EHWIT.EMP_STATUS = '0' 
	AND ECET.VALID != 'I';
	
select EMP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD where JOB_NO = '123122' AND ETP_ID = 'C2311231147301838934081353555974' and VALID!='I'

INSERT INTO `fuyao_user_dev`.`ENT_HR_DEP_FIELD_TD`(`GROUP_ID`, `FIELD_ID`, `ETP_ID`, `FIELD_NAME`, `IS_EXTEND_FIELD`, `IS_STOP_FIELD`, `IS_STOP_USING`, `IS_DELETE`, `FIELD_TYPE`, `IS_REQUIRED`, `SORT`, `EXTEND_FIELD`, `IS_EDIT`, `FIELD_LENGTH`, `EXTEND_FIELD_TYPE`, `TOOLTIP`, `CREATE_TIME`, `LAST_MODI_TIME`) VALUES ('T_ETP_DEPART_INFO_TD1', 'F2401261117541862119453654888449', 'C2305261557471773404862380445703', '分管领导3', '1', '0', '1', '1', '6', '0', 3, '[]', '1', '256', '0', NULL, '2024-01-26 11:17:54', '2024-01-26 11:17:54');
INSERT INTO `fuyao_user_dev`.`ENT_HR_DEP_FIELD_TD`(`GROUP_ID`, `FIELD_ID`, `ETP_ID`, `FIELD_NAME`, `IS_EXTEND_FIELD`, `IS_STOP_FIELD`, `IS_STOP_USING`, `IS_DELETE`, `FIELD_TYPE`, `IS_REQUIRED`, `SORT`, `EXTEND_FIELD`, `IS_EDIT`, `FIELD_LENGTH`, `EXTEND_FIELD_TYPE`, `TOOLTIP`, `CREATE_TIME`, `LAST_MODI_TIME`) VALUES ('T_ETP_DEPART_INFO_TD1', 'F2401261117181862119303041626120', 'C2305261557471773404862380445703', '分管领导1', '1', '0', '1', '1', '6', '0', 1, '[]', '1', '256', '0', NULL, '2024-01-26 11:17:18', '2024-01-26 11:17:18');
INSERT INTO `fuyao_user_dev`.`ENT_HR_DEP_FIELD_TD`(`GROUP_ID`, `FIELD_ID`, `ETP_ID`, `FIELD_NAME`, `IS_EXTEND_FIELD`, `IS_STOP_FIELD`, `IS_STOP_USING`, `IS_DELETE`, `FIELD_TYPE`, `IS_REQUIRED`, `SORT`, `EXTEND_FIELD`, `IS_EDIT`, `FIELD_LENGTH`, `EXTEND_FIELD_TYPE`, `TOOLTIP`, `CREATE_TIME`, `LAST_MODI_TIME`) VALUES ('T_ETP_DEPART_INFO_TD1', 'F2401261117361862119379294072833', 'C2305261557471773404862380445703', '分管领导2', '1', '0', '1', '1', '6', '0', 2, '[]', '1', '256', '0', NULL, '2024-01-26 11:17:36', '2024-01-26 11:17:36');


ALTER TABLE `fuyao_user_dev`.`ENT_HR_POST_ADJUST_APPL_TH` 
-- ADD COLUMN `POST_RANK` varchar(70) NULL COMMENT '岗位' AFTER `JOB_TITILE`;
-- ADD COLUMN `POSITIONS` varchar(70) NULL COMMENT '职级' AFTER `POST_RANK`;
-- ADD COLUMN `EXPECT_POST_RANK` varchar(70) NULL COMMENT '期望调整岗位' AFTER `EXPECT_JOB_TITILE`;
ADD COLUMN `EXPECT_POSITIONS` varchar(70) NULL COMMENT '期望调整职级' AFTER `EXPECT_POST_RANK`;


