屹通.sql

update sys_menu set IS_SHOW = '1'  where MENU_TYPE = '2';

SELECT
	MKT_CUST_INFO.NAME AS ETP_NAME,
	etp_num.EMP_CNT AS STAFF_SIZE,
	pub_industry.INDUSTRY_NAME AS INDUSTRY 
FROM
	app_market_dev.MKT_ARES_ETP_FLAG_INFO ETP_FLAG
	INNER JOIN app_market_dev.MKT_CUST_INFO_TD_VIEW MKT_CUST_INFO ON MKT_CUST_INFO.ETP_ID = ETP_FLAG.ETP_ID
	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = MKT_CUST_INFO.ETP_ID
	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE
	LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = MKT_CUST_INFO.ETP_ID 
WHERE
	ETP_FLAG.INSURANCE_FLAG = '1' 
	AND ETP_FLAG.TENA_ID = 'T20211022190846016130000000097' 
ORDER BY
	ETP_FLAG.CREATE_TIME;


SELECT
*
-- 	organ.ORG_NAME,
-- 	ARES_ETP.NAME AS ETP_NAME
-- 	etp_num.EMP_CNT AS STAFF_SIZE,
-- 	pub_industry.INDUSTRY_NAME AS INDUSTRY 
FROM
	app_market_dev.MKT_ARES_ETP_FLAG_INFO ETP_FLAG
-- 	INNER JOIN app_market_dev.MKT_ARES_ETP_INFO ARES_ETP ON ARES_ETP.ETP_ID = ETP_FLAG.ETP_ID
-- 	LEFT JOIN app_market_dev.sys_organ organ ON ARES_ETP.ORG_ID = organ.ID
-- 	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ARES_ETP.ETP_ID
-- 	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE
-- 	LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = ARES_ETP.ETP_ID 
WHERE
	ETP_FLAG.STAFF_FLAG = '1' 
	AND ETP_FLAG.TENA_ID = 'T20211022190846016130000000097' 
ORDER BY
	ETP_FLAG.CREATE_TIME;

SELECT DISTINCT
	ETP_IN.ETP_ID AS etpId 
FROM
	fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN
	INNER JOIN app_market_dev.MKT_CUST_INFO_TD_VIEW ares_etp ON ETP_IN.ETP_ID = ares_etp.ETP_ID
	LEFT JOIN app_market_dev.MKT_TENA_INFO_TD TENA_INFO ON ETP_IN.APP_ID = TENA_INFO.CODE 
WHERE
	TENA_INFO.TENA_ID = 'T20211022190846016130000000097';
	
SELECT DISTINCT
	ETP_IN.ETP_ID AS etpId 
FROM
	fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN
	INNER JOIN app_market_dev.MKT_ARES_ETP_INFO ares_etp ON ETP_IN.ETP_ID = ares_etp.ETP_ID
	LEFT JOIN app_market_dev.MKT_TENA_INFO_TD TENA_INFO ON ETP_IN.APP_ID = TENA_INFO.CODE 
WHERE
	TENA_INFO.TENA_ID = 'T20231027141354017540000000229';

SELECT
	count( DISTINCT ( ETP_FLAG.ETP_ID ) ) AS PAYROLL_ETP_NUM 
FROM
	MKT_ARES_ETP_FLAG_INFO ETP_FLAG 
WHERE
	ETP_FLAG.TENA_ID = 'T20211022190846016130000000097'
	AND ETP_FLAG.TAX_FLAG = '1'



SELECT
	sum( PAYOFF_RECORD.STAFF_NUM ) AS PAYROLL_EMP_NUM,
	sum( PAYOFF_RECORD.STAFF_AMT ) AS PAYROLL_EMP_AMT 
FROM
	app_market_dev.MKT_TENA_INFO_TD TENA_INFO
	INNER JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD F_ETP_INNFO ON F_ETP_INNFO.APP_ID = TENA_INFO.CODE 
	AND TENA_INFO.TENA_ID = 'T20211022190846016130000000097'
	AND TENA_INFO.TENA_ID = 'T20211022190846016130000000097'
	INNER JOIN app_market_dev.MTK_JX_SHOW_PAYOFF_RECORD PAYOFF_RECORD ON PAYOFF_RECORD.ETP_ID = F_ETP_INNFO.ETP_ID


SELECT
	Amt AS AMT,
	TotalAmt AS TOTAL_AMT,
	INDUSTRY,
	INDUSTRY_CODE,
	ROUND( Amt * 100.0 / TotalAmt, 2 ) AS PERCENTAGE 
FROM
	(
SELECT
	count( MKT_CUST.etp_id ) AS Amt,
	ETP_IN.INDUSTRY_CODE,
	pub_industry.INDUSTRY_NAME AS INDUSTRY 
FROM
	app_market_dev.MKT_CUST_INFO_TD_VIEW MKT_CUST
	INNER JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = MKT_CUST.ETP_ID 
	AND MKT_CUST.TENA_ID = 'T20211022190846016130000000097'
	left JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE 
GROUP BY
	ETP_IN.INDUSTRY_CODE 
	) AS subquery
	CROSS JOIN ( SELECT count( MKT_CUST.etp_id ) AS TotalAmt FROM app_market_dev.MKT_CUST_INFO_TD_VIEW MKT_CUST WHERE MKT_CUST.TENA_ID = 'T20211022190846016130000000097' ) AS total 
ORDER BY
	INDUSTRY;SELECT
	count( MKT_CUST.etp_id ) AS Amt,
	ETP_IN.INDUSTRY_CODE,
	pub_industry.INDUSTRY_NAME AS INDUSTRY 
FROM
	app_market_dev.MKT_CUST_INFO_TD_VIEW MKT_CUST
	INNER JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = MKT_CUST.ETP_ID 
	AND MKT_CUST.TENA_ID = 'T20211022190846016130000000097'
	left JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE 
GROUP BY
	ETP_IN.INDUSTRY_CODE 

SELECT
	sum( PAYOFF_RECORD.STAFF_NUM ) AS PAYROLL_EMP_NUM,
	sum( PAYOFF_RECORD.STAFF_AMT ) AS PAYROLL_EMP_AMT 
FROM
	app_market_dev.MKT_TENA_INFO_TD TENA_INFO
	INNER JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD F_ETP_INNFO ON F_ETP_INNFO.APP_ID = TENA_INFO.CODE 
	AND TENA_INFO.TENA_ID = 'T20231027141354017540000000229'
	INNER JOIN app_market_dev.MTK_JX_SHOW_PAYOFF_RECORD PAYOFF_RECORD ON PAYOFF_RECORD.ETP_ID = F_ETP_INNFO.ETP_ID

SELECT
	sum( PAYOFF_RECORD.STAFF_NUM ) AS PAYROLL_EMP_NUM,
	sum( PAYOFF_RECORD.STAFF_AMT ) AS PAYROLL_EMP_AMT 
FROM
	app_market_dev.MKT_TENA_INFO_TD TENA_INFO
	INNER JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD F_ETP_INNFO ON F_ETP_INNFO.APP_ID = TENA_INFO.CODE 
	AND TENA_INFO.TENA_ID = 'T20231027141354017540000000229'
	INNER JOIN app_market_dev.MTK_JX_SHOW_PAYOFF_RECORD PAYOFF_RECORD ON PAYOFF_RECORD.ETP_ID = F_ETP_INNFO.ETP_ID


SELECT
	sum( etp_num.EMP_CNT ) AS cnt 
FROM
	app_market_dev.MKT_ARES_ETP_INFO ARES_ETP
	LEFT JOIN (
SELECT
	COUNT( EMP_ID ) AS EMP_CNT,
	ETP_ID 
FROM
	fuyao_user_dev.T_CUSTOM_INFO_TD 
WHERE
	VALID != 'I' 
	AND CREATE_TIME <= '2024-03-29 20:41:14' 
GROUP BY
	ETP_ID 
	) etp_num ON etp_num.ETP_ID = ARES_ETP.ETP_ID 
	AND ARES_ETP.TENA_ID = 'T20231027141354017540000000229'

SELECT
			*,
			CASE
				WHEN TT.ETP_STAT = '1' THEN '待激活用户'
				WHEN TT.ETP_STAT = '2' THEN '高价值客户'
				WHEN TT.ETP_STAT = '3' THEN '中价值客户'
				WHEN TT.ETP_STAT = '4' THEN '低价值客户'
				WHEN TT.ETP_STAT = '5' THEN '无价值客户'
				WHEN TT.ETP_STAT = '6' THEN '流失客户'
				ELSE '开通用户'
			END AS ETP_STAT_STR,
			CASE
				TT.IS_SETTLE_ACCOUNTS WHEN '0' THEN '否'
				WHEN '1' THEN '是'
			END 'SETTLE_ACCOUNTS_STR',
			CASE
				WHEN TT.USER_ROLE = '1' THEN '管理者'
				WHEN TT.USER_ROLE = '2' THEN '财务'
				WHEN TT.USER_ROLE = '3' THEN '人事'
				WHEN TT.USER_ROLE = '4' THEN '代发'
				ELSE ''
			END AS USER_ROLE_DESC
		FROM
			(
			SELECT
				T1.CUST_ID,
				T1.TENA_ID,
				T1.EMP_ID,
				T1.ETP_ID,
				T1.EMP_CUST_NO,
				CONCAT(T1.NAME, IF(T1.DISSOLVE = '1', '（解散）', '')) NAME,
				T1.BUYER_NAME,
				T1.BUYER_TEL,
				T1.LOGIN_IP,
				T1.LOGIN_TIME,
				T1.PEAK_VALUE,
				T1.STATUS,
				T1.CREATE_TIME,
				T1.UPDATE_TIME,
				T1.CREATE_MAN,
				T1.LAST_MODI_MAN,
				T1.SPEC_ID,
				T1.PAY_DATE,
				T1.BANK_NAME,
				T1.CUSTOMER_RELATION,
				T1.ORDER_TIME,
				T1.USER_ROLE,
				T4.NAME PROD_NAME,
				T3.NAME SPEC_NAME,
				T1.AMT,
				CASE
					WHEN T1.AMT IS NULL THEN '-'
					ELSE FORMAT(T1.AMT, 2)
				END AS AMT_TXT,
				T1.ORDER_STAT,
				PARAM1.NAME ORDER_STAT_TXT,
				IFNULL(T9.PROV_NAME, T5.NAME) PROV_NAME,
				T6.NAME TENA_NAME,
				LEFT(T1.ORDER_TIME,
				10) ORDER_DATE,
				T3.EFF_DURA,
				T3.EFF_DURA_UNIT,
				CASE
					WHEN T1.CUST_ID IS NULL THEN ''
					WHEN T1.ORDER_STAT != '1' THEN 0
					WHEN T3.EFF_DURA_UNIT = '1' THEN DATEDIFF(DATE_ADD(LEFT(T1.ORDER_TIME, 10), INTERVAL T3.EFF_DURA YEAR ), DATE_FORMAT(NOW(), '%Y-%m-%d'))
					WHEN T3.EFF_DURA_UNIT = '2' THEN DATEDIFF(DATE_ADD(LEFT(T1.ORDER_TIME, 10), INTERVAL T3.EFF_DURA MONTH ), DATE_FORMAT(NOW(), '%Y-%m-%d'))
					WHEN T3.EFF_DURA_UNIT = '3' THEN DATEDIFF( DATE_ADD(LEFT(T1.ORDER_TIME, 10), INTERVAL T3.EFF_DURA DAY ), DATE_FORMAT(NOW(), '%Y-%m-%d'))
					ELSE 0
				END AS LEFT_DAYS,
				CASE
					WHEN ( T1.LOGIN_DATE = ''
					AND T1.ORDER_TIME != '') THEN '1'
					WHEN ( T1.LOGIN_DATE >= DATE_FORMAT(DATE_ADD(now(), INTERVAL -1 MONTH) , "%Y-%m-%d")
					AND T1.COMMISSION_DATE >= DATE_FORMAT(DATE_ADD(now(), INTERVAL -1 MONTH) , "%Y-%m-%d")
					AND T1.ORDER_TIME != '') THEN '2'
					WHEN ( T1.LOGIN_DATE >= DATE_FORMAT(DATE_ADD(now(), INTERVAL -1 MONTH) , "%Y-%m-%d")
					AND T1.COMMISSION_DATE < DATE_FORMAT(DATE_ADD(now(), INTERVAL -1 MONTH) , "%Y-%m-%d")
					AND T1.COMMISSION_DATE != ''
					AND T1.ORDER_TIME != '') THEN '3'
					WHEN ( T1.LOGIN_DATE >= DATE_FORMAT(DATE_ADD(now(), INTERVAL -1 MONTH) , "%Y-%m-%d")
					AND T1.COMMISSION_DATE = ''
					AND T1.ORDER_TIME != '') THEN '4'
					WHEN ( T1.LOGIN_DATE < DATE_FORMAT(DATE_ADD(now(), INTERVAL -1 MONTH) , "%Y-%m-%d")
					AND T1.LOGIN = '0'
					AND T1.COMMISSION_DATE = ''
					AND T1.ORDER_TIME != '') THEN '5'
					WHEN ( T1.LOGIN_DATE < DATE_FORMAT(DATE_ADD(now(), INTERVAL -1 MONTH) , "%Y-%m-%d")
					AND T1.COMMISSION_DATE != ''
					AND T1.ORDER_TIME != '') THEN '6'
					WHEN ( T1.ORDER_TIME >= DATE_FORMAT(DATE_ADD(now(), INTERVAL -1 MONTH) , "%Y-%m-%d")) THEN '7'
					ELSE '0'
				END AS ETP_STAT,
				T7.TYPE_ID,
				T7.TYPE_TXT,
				MODT.ROADSHOW_LEAD AS MAIN_NAME,
				MODT.ETP_CNT STAFF_SIZE,
				MODT.ETP_CNT STAFF_SIZE_STR,
				T1.INDUSTRY INDUSTRY_CODE,
				MADT.SETTLE_ACCOUNTS_DATE,
				CASE
					WHEN (T1.COMMISSION_DATE = ''
					or T1.COMMISSION_DATE is NULL) THEN ''
					ELSE CONCAT(SUBSTR(T1.COMMISSION_DATE, 1, 4), '年', SUBSTR(T1.COMMISSION_DATE, 6, 2), '月', SUBSTR(T1.COMMISSION_DATE, 9, 2), '日')
				END AS COMMISSION_DATE,
				CASE
					WHEN (T1.LOGIN_DATE = ''
					or T1.LOGIN_DATE is NULL) THEN ''
					ELSE CONCAT(SUBSTR(T1.LOGIN_DATE, 1, 4), '年', SUBSTR(T1.LOGIN_DATE, 6, 2), '月', SUBSTR(T1.LOGIN_DATE, 9, 2), '日')
				END AS LOGIN_DATE,
				CASE
					WHEN (T1.FIRST_COMMISSION_DATE = ''
					or T1.FIRST_COMMISSION_DATE is NULL) THEN ''
					ELSE CONCAT(SUBSTR(T1.FIRST_COMMISSION_DATE, 1, 4), '年', SUBSTR(T1.FIRST_COMMISSION_DATE, 6, 2), '月', SUBSTR(T1.FIRST_COMMISSION_DATE, 9, 2), '日')
				END AS FIRST_COMMISSION_DATE,
				T1.LOGIN,
				CASE
					WHEN MADT.ETP_ID is null THEN '0'
					ELSE '1'
				END AS IS_SETTLE_ACCOUNTS,
				T1.EMP_NUMBER,
				T1.SMAR_EMP_NUMBER
			FROM
				(
				SELECT
					*
				FROM
					(
					SELECT
						MCIT.*,
						MOIT.SPEC_ID,
						MOIT.AMT,
						MOIT.ORDER_STAT,
						MOIT.ORDER_TIME
					FROM
						app_market_dev.MKT_CUST_INFO_TD MCIT
					LEFT JOIN app_market_dev.MKT_ORDER_INFO_TD MOIT ON
						MOIT.CUST_ID = MCIT.CUST_ID
					WHERE
						MCIT.DISMISS = '0'
						AND EXISTS (
						SELECT
							1
						FROM
							app_market_dev.MKT_CUST_PROD_INFO_TM MCPIT
						WHERE
							MCPIT.CUST_ID = MCIT.CUST_ID
							AND MCPIT.PROD_STAT = '1' )
						AND MCIT.TENA_ID = 'T20231027141354017540000000229'
					ORDER BY
						MOIT.ORDER_TIME DESC ) T
				GROUP BY
					T.CUST_ID ) T1
			LEFT JOIN app_market_dev.MKT_BASE_PROD_SPEC_TM T3 ON
				T3.SPEC_ID = T1.SPEC_ID
			LEFT JOIN app_market_dev.MKT_BASE_PROD_INFO_TD T4 ON
				T4.PROD_ID = T3.PROD_ID
			LEFT JOIN app_market_dev.MKT_PROV_INFO_TD T5 ON
				T5.PROV_ID = T4.PROV_ID
			LEFT JOIN (
				SELECT
					PRODS_ID,
					GROUP_CONCAT(OROD_ID) PROD_IDS,
					GROUP_CONCAT(DISTINCT MPIT.NAME) PROV_NAME
				FROM
					app_market_dev.MKT_PROD_PACK_TM MPPT
				LEFT JOIN app_market_dev.MKT_BASE_PROD_INFO_TD MBPIT ON
					MPPT.OROD_ID = MBPIT.PROD_ID
				LEFT JOIN app_market_dev.MKT_PROV_INFO_TD MPIT ON
					MBPIT.PROV_ID = MPIT.PROV_ID
				GROUP BY
					PRODS_ID ) T9 ON
				T3.PROD_ID = T9.PRODS_ID
			LEFT JOIN app_market_dev.MKT_TENA_INFO_TD T6 ON
				T6.TENA_ID = T1.TENA_ID
			LEFT JOIN (
				SELECT
					TT1.PROD_ID,
					GROUP_CONCAT(TT1.TYPE_ID) TYPE_ID,
					GROUP_CONCAT(TT2.NAME) TYPE_TXT
				FROM
					app_market_dev.MKT_PROD_TYPE_TM TT1
				LEFT JOIN app_market_dev.MKT_PARAM_INFO_TC TT2 ON
					TT2.PARAM_ID = TT1.TYPE_ID
				GROUP BY
					TT1.PROD_ID ) T7 ON
				T7.PROD_ID = T4.PROD_ID
			LEFT JOIN app_market_dev.MKT_PARAM_INFO_TC PARAM1 ON
				T1.ORDER_STAT = PARAM1.CODE
				AND PARAM1.PARA_ID = (
				SELECT
					PARAM_ID
				FROM
					app_market_dev.MKT_PARAM_INFO_TC
				WHERE
					CODE = 'CUST_PROD_STAT'
					AND DEL_FLG = '1')
			LEFT JOIN app_market_dev.MKT_SALARY_RECORD_TH MODT ON
				T1.TENA_ID = MODT.TENA_ID
				AND T1.ETP_ID = MODT.ETP_ID
			LEFT JOIN (
				SELECT
					TENA_ID,
					ETP_ID,
					MAX(DATE) SETTLE_ACCOUNTS_DATE
				FROM
					app_market_dev.MKT_ACCOUNT_DETAILS_TD
				WHERE
					PROD_ID in ( 'P20210705152752016030000002178', 'P20220830151313110980000003027')
						AND COST_AMT != '0'
					GROUP BY
						TENA_ID,
						ETP_ID ) MADT ON
				T1.TENA_ID = MADT.TENA_ID
				AND T1.ETP_ID = MADT.ETP_ID
			WHERE
				T6.TENA_ID = 'T20231027141354017540000000229' ) TT
		ORDER BY
			TT.ORDER_TIME DESC;


SELECT
						MCIT.*,
						MOIT.SPEC_ID,
						MOIT.AMT,
						MOIT.ORDER_STAT,
						MOIT.ORDER_TIME
					FROM
						app_market_dev.MKT_CUST_INFO_TD MCIT
					inner JOIN app_market_dev.MKT_ORDER_INFO_TD MOIT ON
						MOIT.CUST_ID = MCIT.CUST_ID
					WHERE
						MCIT.DISMISS = '0'
						AND EXISTS (
						SELECT
							1
						FROM
							app_market_dev.MKT_CUST_PROD_INFO_TM MCPIT
						WHERE
							MCPIT.CUST_ID = MCIT.CUST_ID
							AND MCPIT.PROD_STAT = '1' )
						AND MCIT.TENA_ID = 'T20231027141354017540000000229'
					ORDER BY
						MOIT.ORDER_TIME DESC ;

SELECT
	Amt AS AMT,
	TotalAmt AS TOTAL_AMT,
	INDUSTRY,
	ROUND( Amt * 100.0 / TotalAmt, 2 ) AS PERCENTAGE 
FROM
	(
SELECT
	count( MKT_CUST.etp_id ) AS Amt,
	ETP_IN.INDUSTRY_CODE,
	pub_industry.INDUSTRY_NAME AS INDUSTRY 
FROM
	app_market_dev.MKT_CUST_INFO_TD MKT_CUST
	inner JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = MKT_CUST.ETP_ID 
	AND MKT_CUST.TENA_ID = 'T20231027141354017540000000229' 
	inner JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE 
GROUP BY
	ETP_IN.INDUSTRY_CODE 
	) AS subquery
	CROSS JOIN ( SELECT count( MKT_CUST.etp_id ) AS TotalAmt FROM app_market_dev.MKT_CUST_INFO_TD MKT_CUST WHERE MKT_CUST.TENA_ID = 'T20231027141354017540000000229'  ) AS total 
ORDER BY
	INDUSTRY;
SELECT
	Amt AS AMT,
	INDUSTRY,
	ROUND( Amt * 100.0 / TotalAmt, 2 ) AS PERCENTAGE 
FROM
	(
SELECT
	count( MKT_CUST.ETP_ID ) AS Amt,
	ETP_IN.INDUSTRY_CODE,
	pub_industry.INDUSTRY_NAME AS INDUSTRY 
FROM
	app_market_dev.MKT_CUST_INFO_TD MKT_CUST
	left JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = MKT_CUST.ETP_ID
	left JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE 
WHERE
	MKT_CUST.TENA_ID = 'T20231027141354017540000000229' 
GROUP BY
	ETP_IN.INDUSTRY_CODE 
	) AS subquery
	CROSS JOIN ( SELECT count( etp_id ) AS TotalAmt FROM app_market_dev.MKT_CUST_INFO_TD MKT_CUST WHERE TENA_ID = 'T20231027141354017540000000229' ) AS total


INSERT INTO `app_market_dev`.`sys_organ`(`ID`, `INCORP_NO`, `PARENT_ID`, `PARENT_IDS`, `AREA_ID`, `CODE`, `ORG_NAME`, `ORG_TYPE`, `GRADE`, `ADDRESS`, `ZIP_CODE`, `MASTER`, `PHONE`, `FAX`, `EMAIL`, `CREATE_BY`, `CREATE_DATE`, `UPDATE_BY`, `UPDATE_DATE`, `REMARKS`, `DEL_FLAG`, `ORG_VALID`, `TENA_ID`, `PRO_CODE`) VALUES ('O20240329141955016800000000399', NULL, '0', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-03-29 14:43:09', NULL, NULL, NULL, '1', '1', 'T20231027141354017540000000229', NULL);


sum(etp_num.EMP_CNT) as cnt
		from app_market_dev.MKT_CUST_INFO_TD MKT_CUST
		LEFT JOIN (
		SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' and
		  CREATE_TIME<= ?   GROUP BY ETP_ID
		GROUP BY ETP_ID
		where
		  CREATE_TIME<= ?  
		) etp_num ON etp_num.ETP_ID = MKT_CUST.ETP_ID and  MKT_CUST.TENA_ID = ?
		
		
		 select sum(etp_num.EMP_CNT) as cnt from app_market_dev.MKT_CUST_INFO_TD MKT_CUST LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' and CREATE_TIME<= '2024-03-29 13:39:23' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = MKT_CUST.ETP_ID and MKT_CUST.TENA_ID =null;
		 'T20231027141354017540000000229'
		 
		 
SELECT
	INSU_RECORD.INSURANCE_NUM  AS PAYROLL_ETP_NUM 
FROM
	app_market_dev.MTK_JX_SHOW_INSU_RECORD INSU_RECORD 
WHERE
	INSU_RECORD.TENANT_ID = 'T20231027141354017540000000229'

SELECT
	COUNT( cust_info.EMP_ID ) AS AMT,
	F_ETP_INNFO.ETP_ID,
	F_ETP_INNFO.ETP_NAME,
	ROW_NUMBER ( ) OVER ( ORDER BY COUNT( cust_info.EMP_ID ) DESC ) AS ETP_CODE 
FROM
	app_market_dev.MKT_TENA_INFO_TD TENA_INFO
	INNER JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD F_ETP_INNFO ON F_ETP_INNFO.APP_ID = TENA_INFO.CODE 
	AND TENA_INFO.TENA_ID = 'T20231027141354017540000000229'
	INNER JOIN fuyao_user_dev.T_CUSTOM_INFO_TD cust_info ON cust_info.ETP_ID = F_ETP_INNFO.ETP_ID 
	AND cust_info.VALID != 'I'
	INNER JOIN app_market_dev.MKT_ARES_ETP_INFO ARES_ETP ON ARES_ETP.ETP_ID = cust_info.ETP_ID 
GROUP BY
	F_ETP_INNFO.ETP_ID,
	F_ETP_INNFO.ETP_NAME 
ORDER BY
	AMT DESC 
	LIMIT 10;


SELECT
	Amt AS AMT,
	TotalAmt AS TOTAL_AMT,
	INDUSTRY,
	ROUND( Amt * 100.0 / TotalAmt, 2 ) AS PERCENTAGE 
FROM
	(
SELECT
	count( MKT_CUST.etp_id ) AS Amt,
	ETP_IN.INDUSTRY_CODE,
	pub_industry.INDUSTRY_NAME AS INDUSTRY 
FROM
	app_market_dev.MKT_CUST_INFO_TD MKT_CUST
	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = MKT_CUST.ETP_ID 
	AND MKT_CUST.TENA_ID = 'T20231027141354017540000000229'
	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE 
GROUP BY
	ETP_IN.INDUSTRY_CODE 
	) AS subquery
	CROSS JOIN ( SELECT count( MKT_CUST.etp_id ) AS TotalAmt FROM app_market_dev.MKT_CUST_INFO_TD MKT_CUST WHERE MKT_CUST.TENA_ID = 'T20231027141354017540000000229' ) AS total 
ORDER BY
	INDUSTRY;

SELECT
	F_ETP_INNFO.ETP_NAME,
	etp_num.EMP_CNT AS STAFF_SIZE,
	pub_industry.INDUSTRY 
FROM
	app_market_dev.MKT_TENA_INFO_TD TENA_INFO
	INNER JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD F_ETP_INNFO ON F_ETP_INNFO.APP_ID = TENA_INFO.CODE 
	AND TENA_INFO.TENA_ID = 'T20231027141354017540000000229'
	INNER JOIN app_market_dev.MKT_CUST_INFO_TD ETP_FLAG ON F_ETP_INNFO.ETP_ID = ETP_FLAG.ETP_ID
	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = F_ETP_INNFO.INDUSTRY_CODE
	LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = F_ETP_INNFO.ETP_ID

select count(ETP_ID) as c,ETP_ID from MKT_ARES_ETP_FLAG_INFO group by ETP_ID

SELECT
	ETP_ID,TENA_ID,
	TAX_FLAG 
FROM
	app_market_dev.MKT_ARES_ETP_FLAG_INFO 
WHERE
-- 	TENA_ID = 'T20231027141354017540000000229' 
-- 	AND 
	ETP_ID = 'C2403150859101879841547318255618'

SELECT
	Amt AS AMT,
	INDUSTRY,
	ROUND( Amt * 100.0 / TotalAmt, 2 ) AS PERCENTAGE 
FROM
	(
SELECT
	count( ares_etp.etp_id ) AS Amt,
	ETP_IN.INDUSTRY_CODE,
	pub_industry.INDUSTRY_NAME AS INDUSTRY 
FROM
	app_market_dev.MKT_ARES_ETP_INFO ares_etp
	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ares_etp.ETP_ID 
	AND ares_etp.ORG_ID = '1003'
	inner JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE 
WHERE
	ares_etp.TENA_ID = 'T20231027141354017540000000229' 
GROUP BY
	ETP_IN.INDUSTRY_CODE 
	) AS subquery
	CROSS JOIN ( SELECT count( etp_id ) AS TotalAmt FROM app_market_dev.MKT_ARES_ETP_INFO WHERE TENA_ID = 'T20231027141354017540000000229' AND ORG_ID = '1003' ) AS total;


SELECT
	organ.ORG_NAME,
	ARES_ETP.NAME AS ETP_NAME,
	etp_num.EMP_CNT AS STAFF_SIZE,
	pub_industry.INDUSTRY_NAME AS INDUSTRY 
FROM
	app_market_dev.MKT_ARES_ETP_FLAG_INFO ETP_FLAG
	INNER JOIN app_market_dev.MKT_ARES_ETP_INFO ARES_ETP ON ARES_ETP.ETP_ID = ETP_FLAG.ETP_ID
	LEFT JOIN app_market_dev.sys_organ organ ON ARES_ETP.ORG_ID = organ.ID
	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ARES_ETP.ETP_ID
	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE
	LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = ARES_ETP.ETP_ID 
WHERE
	ETP_FLAG.STAFF_FLAG = '1' 
	AND ETP_FLAG.TENA_ID = 'T20231027141354017540000000229' 
ORDER BY
	ETP_FLAG.CREATE_TIME 
	) t 
	) tt,
	( SELECT @rownum := 0 ) k,
	(
SELECT
	count( 1 ) num 
FROM
	(
SELECT
	organ.ORG_NAME,
	ARES_ETP.NAME AS ETP_NAME,
	etp_num.EMP_CNT AS STAFF_SIZE,
	pub_industry.INDUSTRY_NAME AS INDUSTRY 
FROM
	app_market_dev.MKT_ARES_ETP_FLAG_INFO ETP_FLAG
	INNER JOIN app_market_dev.MKT_ARES_ETP_INFO ARES_ETP ON ARES_ETP.ETP_ID = ETP_FLAG.ETP_ID
	LEFT JOIN app_market_dev.sys_organ organ ON ARES_ETP.ORG_ID = organ.ID
	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ARES_ETP.ETP_ID
	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE
	LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = ARES_ETP.ETP_ID 
WHERE
	ETP_FLAG.STAFF_FLAG = '1' 
	AND ETP_FLAG.TENA_ID = 'T20231027141354017540000000229' 
ORDER BY
	ETP_FLAG.CREATE_TIME;

SELECT ID as ORG_ID
		FROM SYS_ORGAN
		where
			DEL_FLAG = '1'
			AND  PARENT_ID is null
			AND  TENA_ID = 'T20231027141354017540000000229';

SELECT
	* 
FROM
	(
SELECT
	CAST( c.num AS CHAR ) AS TOTAL_NUM,
	tt.* 
FROM
	(
SELECT
	@rownum := @rownum + 1 AS rn,
	t.* 
FROM
	(
SELECT
	MKT_CUST.NAME AS ETP_NAME,
	ares_etp.ETP_ID,
	ares_etp.ID,
	pub_industry.INDUSTRY_NAME AS INDUSTRY,
	etp_num.EMP_CNT AS STAFF_SIZE,
	sys_organ.ORG_NAME,
	MKT_CUST.CUST_ID 
FROM
	app_market_dev.MKT_ARES_ETP_INFO ares_etp
	INNER JOIN app_market_dev.MKT_CUST_INFO_TD MKT_CUST ON MKT_CUST.ETP_ID = ares_etp.ETP_ID 
	AND ares_etp.ORG_ID = '1000'
	LEFT JOIN app_market_dev.sys_organ sys_organ ON sys_organ.ID = ares_etp.ORG_ID
	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ares_etp.ETP_ID
	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE
	LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = ares_etp.ETP_ID 
WHERE
	ares_etp.TENA_ID = 'T20231027141354017540000000229' 
ORDER BY
	MKT_CUST.NAME 
	) t 
	) tt,
	( SELECT @rownum := 0 ) k,
	(
SELECT
	count( 1 ) num 
FROM
	(
SELECT
	MKT_CUST.NAME AS ETP_NAME,
	ares_etp.ETP_ID,
	ares_etp.ID,
	pub_industry.INDUSTRY_NAME AS INDUSTRY,
	etp_num.EMP_CNT AS STAFF_SIZE,
	sys_organ.ORG_NAME,
	MKT_CUST.CUST_ID 
FROM
	app_market_dev.MKT_ARES_ETP_INFO ares_etp
	INNER JOIN app_market_dev.MKT_CUST_INFO_TD MKT_CUST ON MKT_CUST.ETP_ID = ares_etp.ETP_ID 
	AND ares_etp.ORG_ID = '1000'
	LEFT JOIN app_market_dev.sys_organ sys_organ ON sys_organ.ID = ares_etp.ORG_ID
	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ares_etp.ETP_ID
	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE
	LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = ares_etp.ETP_ID 
WHERE
	ares_etp.TENA_ID = 'T20231027141354017540000000229' 
ORDER BY
	MKT_CUST.NAME 
	) rw 
	) c 
	) row_ 
WHERE
	row_.rn <= 11;



SELECT
	organ.ORG_NAME,
	ARES_ETP.NAME AS ETP_NAME,
	etp_num.EMP_CNT AS STAFF_SIZE,
	pub_industry.INDUSTRY_NAME AS INDUSTRY
FROM
	app_market_dev.MKT_ARES_ETP_FLAG_INFO ETP_FLAG
	INNER JOIN app_market_dev.MKT_ARES_ETP_INFO ARES_ETP ON ARES_ETP.ETP_ID = ETP_FLAG.ETP_ID
	LEFT JOIN app_market_dev.sys_organ organ ON ARES_ETP.ORG_ID = organ.ID 
	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ARES_ETP.ETP_ID
	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE
	LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = ARES_ETP.ETP_ID
WHERE
	ETP_FLAG.STAFF_FLAG = '1' 
	AND ETP_FLAG.TENA_ID = 'T20231027141354017540000000229' 
ORDER BY
	ETP_FLAG.CREATE_TIME
 
 
 
 select * from ( select CAST(c.num AS CHAR) as TOTAL_NUM,tt.* from ( select @rownum:=@rownum+1 as rn , t.* from ( select MKT_CUST.NAME as ETP_NAME ,ares_etp.ETP_ID ,ares_etp.ID ,pub_industry.INDUSTRY_NAME as INDUSTRY ,etp_num.EMP_CNT as STAFF_SIZE ,sys_organ.ORG_NAME ,MKT_CUST.CUST_ID from app_market_dev.MKT_ARES_ETP_INFO ares_etp INNER JOIN app_market_dev.MKT_CUST_INFO_TD MKT_CUST ON MKT_CUST.ETP_ID = ares_etp.ETP_ID and ares_etp.ORG_ID = '1003' LEFT JOIN app_market_dev.sys_organ sys_organ ON sys_organ.ID = ares_etp.ORG_ID LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ares_etp.ETP_ID LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE LEFT JOIN (SELECT COUNT(EMP_ID) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID !='I' group by ETP_ID) etp_num on etp_num.ETP_ID = ares_etp.ETP_ID where ares_etp.TENA_ID = 'T20231027141354017540000000229' order by MKT_CUST.NAME ) t ) tt,(select @rownum:=0) k, (select count(1) num from ( 
			SELECT
				MKT_CUST.NAME AS ETP_NAME,
				ares_etp.ETP_ID,
				ares_etp.ID,
				pub_industry.INDUSTRY_NAME AS INDUSTRY,
				etp_num.EMP_CNT AS STAFF_SIZE,
				sys_organ.ORG_NAME,
				MKT_CUST.CUST_ID 
			FROM
				app_market_dev.MKT_ARES_ETP_INFO ares_etp
				INNER JOIN app_market_dev.MKT_CUST_INFO_TD MKT_CUST ON MKT_CUST.ETP_ID = ares_etp.ETP_ID 
-- 				AND ares_etp.ORG_ID = '1003'
				LEFT JOIN app_market_dev.sys_organ sys_organ ON sys_organ.ID = ares_etp.ORG_ID
				LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ares_etp.ETP_ID
				LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE
				LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = ares_etp.ETP_ID 
			WHERE
				ares_etp.TENA_ID = 'T20231027141354017540000000229' 
			ORDER BY
				MKT_CUST.NAME
 
 ) rw) c ) row_ where row_.rn <=11;


select org.ORG_NAME from sys_organ org left join MKT_TENA_USER_INFO_TB USER_INFO on USER_INFO.ORG_ID = org.ID where USER_INFO.USER_ID = "U20240327181330016320000000718";

SELECT
	Amt AS AMT,
	INDUSTRY,
	ROUND( Amt * 100.0 / TotalAmt, 2 ) AS PERCENTAGE 
FROM
	(
SELECT
	count( ares_etp.etp_id ) AS Amt,
	ETP_IN.INDUSTRY_CODE,
	pub_industry.INDUSTRY_NAME AS INDUSTRY 
FROM
	app_market_dev.MKT_ARES_ETP_INFO ares_etp
	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ares_etp.ETP_ID
	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE 
WHERE
	ares_etp.TENA_ID = '' 
	AND pub_industry.INDUSTRY_NAME = '' 
GROUP BY
	ETP_IN.INDUSTRY_CODE 
	) AS subquery
	CROSS JOIN ( SELECT count( etp_id ) AS TotalAmt FROM app_market_dev.MKT_ARES_ETP_INFO WHERE TENA_ID = '' ) AS total;

SELECT
	MKT_CUST.NAME AS ETP_NAME,
	ares_etp.ETP_ID,
	ares_etp.ID,
	pub_industry.INDUSTRY_NAME AS INDUSTRY,
	etp_num.EMP_CNT AS STAFF_SIZE,
	sys_organ.ORG_NAME,
	MKT_CUST.CUST_ID 
FROM
	app_market_dev.MKT_ARES_ETP_INFO ares_etp
	INNER JOIN app_market_dev.MKT_CUST_INFO_TD MKT_CUST ON MKT_CUST.ETP_ID = ares_etp.ETP_ID
	LEFT JOIN app_market_dev.sys_organ sys_organ ON sys_organ.ID = ares_etp.ORG_ID
	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ares_etp.ETP_ID
	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE
	LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = ares_etp.ETP_ID 
WHERE
	ares_etp.TENA_ID = 'T20211022190846016130000000097' 
	AND MKT_CUST.NAME LIKE concat( '%', '飞', '%' )

SELECT
	ares_etp.NAME AS ETP_NAME,
	ares_etp.ETP_ID,
	ares_etp.INDUSTRY,
	ares_etp.STAFF_SIZE,
	ares_etp.ORG_ID ,
	sys_organ.ORG_NAME 
FROM
	app_market_dev.MKT_ARES_ETP_INFO ares_etp
	LEFT JOIN app_market_dev.sys_organ sys_organ ON sys_organ.ID = ares_etp.ORG_ID 
WHERE
	ares_etp.TENA_ID = 'T20211022190846016130000000097';
	
	
	select ares_etp.NAME as ETP_NAME ,ares_etp.ETP_ID ,ares_etp.ID ,pub_industry.INDUSTRY_NAME as INDUSTRY ,etp_num.EMP_CNT as STAFF_SIZE ,sys_organ.ORG_NAME ,MKT_CUST.CUST_ID from app_market_dev.MKT_ARES_ETP_INFO ares_etp INNER JOIN app_market_dev.MKT_CUST_INFO_TD MKT_CUST ON MKT_CUST.ETP_ID = ares_etp.ETP_ID LEFT JOIN app_market_dev.sys_organ sys_organ ON sys_organ.ID = ares_etp.ORG_ID LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ares_etp.ETP_ID LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE LEFT JOIN (SELECT COUNT(EMP_ID) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID !='I' group by ETP_ID) etp_num on etp_num.ETP_ID = ares_etp.ETP_ID where ares_etp.TENA_ID = 'T20220820184327017430000000580';



	SELECT
ETP_FLAG.*
-- 	organ.ORG_NAME,
-- 	ARES_ETP.NAME AS ETP_NAME,
-- 	ARES_ETP.STAFF_SIZE,
-- 	ARES_ETP.INDUSTRY 
FROM
	app_market_dev.MKT_ARES_ETP_FLAG_INFO ETP_FLAG
-- 	LEFT JOIN app_market_dev.MKT_ARES_ETP_INFO ARES_ETP ON ARES_ETP.ETP_ID = ETP_FLAG.ETP_ID
-- 	LEFT JOIN app_market_dev.sys_organ organ ON ARES_ETP.ORG_ID = organ.ID 
WHERE
	ETP_FLAG.TAX_FLAG = '1' 
	AND ETP_FLAG.TENA_ID = 'T20231027141354017540000000229' 
ORDER BY
	ETP_FLAG.CREATE_TIME 

	INSERT INTO `app_market_dev`.`sys_role`(`ROLE_ID`, `ROLE_NAME`, `REMARK`, `CREATE_BY`, `CREATE_DATE`, `UPDATE_BY`, `UPDATE_DATE`, `DEL_FLAG`, `TENANT_ID`) VALUES ('S20210526151518073300000000007', '普通管理员', '普通管理员', 'sys', NULL, '', NULL, '1', 'C2311161112101836388472780242952');

INSERT INTO MTK_JX_SHOW_TAX_RECORD (  ETP_ID, TAX_NUM, TENANT_ID, TAX_AMT, OPT_DATE, DATE_FLAG )
VALUES
	( "C2403150859101879841547318255618", "3", "T20231027141354017540000000229", "901200008", null, "0" ) 
	ON DUPLICATE KEY UPDATE TAX_NUM =
VALUES
	( TAX_NUM ),
	TAX_AMT =
VALUES
	( TAX_AMT ),
	OPT_DATE =
VALUES
	( OPT_DATE )


SELECT
	u.*,
	o.ORG_NAME,
	r.ROLE_NAME 
FROM
	app_market_dev.MKT_SYS_USER_INFO_TB u
	LEFT JOIN app_market_dev.SYS_ORGAN o ON u.ORG_ID = o.ID
	LEFT JOIN app_market_dev.SYS_USER_ROLE ur ON ur.USER_ID = u.USER_ID
	LEFT JOIN app_market_dev.SYS_ROLE r ON r.ROLE_ID = ur.ROLE_ID 
WHERE
	( u.ORG_ID = 'null' OR o.PARENT_IDS LIKE CONCAT( '%', 'null', '%' ) ) 
ORDER BY
	u.UPDATE_TIME;
	
	
update MKT_TENA_USER_INFO_TB set UPD_TIME = '5200'

SELECT u.*, o.ORG_NAME, r.ROLE_NAME FROM app_market_dev.MKT_TENA_USER_INFO_TB u LEFT JOIN app_market_dev.SYS_ORGAN o ON u.ORG_ID = o.ID LEFT JOIN app_market_dev.SYS_USER_ROLE ur ON ur.USER_ID = u.USER_ID LEFT JOIN app_market_dev.SYS_ROLE r ON r.ROLE_ID = ur.ROLE_ID ORDER BY u.UPDATE_TIME;



INSERT INTO `app_market_dev`.`MKT_TENA_USER_INFO_TB`(`USER_ID`, `TENA_ID`, `NAME`, `ACCOUNT`, `PASSWORD`, `MOBILE`, `EMAIL`, `AVAT_ID`, `ACCT_STAT`, `TYPE`, `ERR_LGN_CNT`, `RSET_PSW_MARK`, `LOGIN_IP`, `LOGIN_TIME`, `CREATE_TIME`, `UPDATE_TIME`, `CREATE_MAN`, `LAST_MODI_MAN`, `ORG_ID`) VALUES ('U20220714151434016960000000495', 'T20220707105048016580000000130', 'tong', 'BBW_001', 'e10adc3949ba59abbe56e057f20f883e', '18155604372', 'tong', NULL, '1', '1', NULL, NULL, NULL, NULL, '2022-07-14 15:14:34', '2022-07-14 15:14:34', 'U20211025091949016110000000264', 'U20211025091949016110000000264', '5200');

show processlist;

show variables like 'log_bin';
SHOW VARIABLES LIKE "general_log%";
show variables like 'slow_query_log_file';



SELECT
	menu.MENU_ID,
	menu.MENU_NAME 
FROM
	app_market_dev.sys_menu menu
	INNER JOIN app_market_dev.sys_role_menu role_menu ON role_menu.MENU_ID = menu.MENU_ID
	INNER JOIN app_market_dev.sys_user_role user_role ON user_role.ROLE_ID = role_menu.ROLE_ID
	INNER JOIN app_market_dev.MKT_SYS_USER_INFO_TB USER_INFO_TB ON USER_INFO_TB.USER_ID = user_role.USER_ID 
WHERE
	USER_INFO_TB.USER_ID = 'U20220521114556016150000000025' 
	AND 
	menu.TENANT_ID = 'T20220820184327017430000000580';


select
	menu.MENU_ID
	,
	menu.MENU_NAME
from
	sys_menu menu
inner join sys_role_menu role_menu
on
	role_menu.MENU_ID = menu.MENU_ID
inner join sys_user_role user_role 
	on
	user_role.ROLE_ID = role_menu.ROLE_ID
inner join
	MKT_SYS_USER_INFO_TB USER_INFO_TB
	on
	USER_INFO_TB.USER_ID = user_role.USER_ID
where
	menu.TENANT_ID = "T20220820184327017430000000580"
	and USER_INFO_TB.USER_ID = 'S20210530105013105990000000006';



select
	menu.*,
	USER_INFO_TB.USER_ID
from
	sys_menu menu
left join sys_role_menu role_menu
on
	role_menu.MENU_ID = menu.MENU_ID
left join sys_role role 
	on
	role.ROLE_ID = role_menu.ROLE_ID
left join sys_user_role user_role 
	on
	user_role.ROLE_ID = role_menu.ROLE_ID
left join
	MKT_SYS_USER_INFO_TB USER_INFO_TB
	on
	USER_INFO_TB.USER_ID = user_role.USER_ID
where
	menu.TENANT_ID = "1";




select sum(JX_RECORD.INSURANCE_NUM) from MTK_JX_SHOW_DATA_RECORD JX_RECORD where JX_RECORD.ETP_ID in (SELECT
								  DISTINCT ETP_IN.ETP_ID
					  FROM fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN
							   LEFT JOIN
						   MKT_TENA_INFO_TD TENA_INFO
						   ON ETP_IN.APP_ID = TENA_INFO.CODE
					  where
								  TENA_INFO.TENA_ID = '')

select count( DISTINCT ( ARES_ETP.ETP_ID ) ) from MKT_ARES_ETP_INFO ARES_ETP;

SELECT
	count( DISTINCT ( ETP_ID ) ) as 实发企业数
FROM
	MKT_ARES_ETP_FLAG_INFO ETP_FLAG 
WHERE
	ETP_FLAG.TENA_ID = ""
	 ETP_FLAG.TAX_FLAG = '1';

select organ.ORG_NAME,ARES_ETP.NAME,ARES_ETP.STAFF_SIZE,ARES_ETP.INDUSTRY
from MKT_ARES_ETP_FLAG_INFO ETP_FLAG 
left join MKT_ARES_ETP_INFO ARES_ETP ON ARES_ETP.ETP_ID = ETP_FLAG.ETP_ID and ETP_FLAG.TENA_ID= ""
left join sys_organ organ ON ARES_ETP.ORG_ID = organ.ID
where ETP_FLAG.TAX_FLAG = '1';

CREATE TABLE `MKT_ARES_ETP_FLAG_INFO` (
  `ID` varchar(64) NOT NULL COMMENT '编码',
  `ETP_ID` varchar(64) DEFAULT NULL COMMENT '企业编码',
  `TENA_ID` varchar(64) DEFAULT NULL COMMENT '租户编码',
  `TAX_FLAG` varchar(8) DEFAULT NULL COMMENT '个税0未开通 1已开通',
  `CREATE_TIME` varchar(26) DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` varchar(26) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='企业辖区信息表';


SELECT
	TENA_INFO.`NAME`,
	sys_role.ROLE_ID,
	sys_role.`ROLE_NAME`,
	sys_role.ROLE_TYPE 
FROM
	MKT_TENA_INFO_TD TENA_INFO
	LEFT JOIN sys_role ON sys_role.TENANT_ID = TENA_INFO.TENA_ID 
ORDER BY
	TENA_INFO.`NAME`,
	sys_role.ROLE_TYPE;

SELECT
	T1.*,
	T2.IS_AWHITE 
FROM
	app_market_dev.MKT_TENA_USER_INFO_TB T1,
	MKT_TENA_INFO_TD T2 
WHERE
	T1.TENA_ID = T2.TENA_ID 
	AND T1.ACCOUNT = 'BJ_001' 
	AND T1.ACCT_STAT = '1'


SELECT
	ares_etp.NAME AS ETP_NAME,
	ares_etp.ID,
	ares_etp.INDUSTRY,
	ares_etp.STAFF_SIZE,
	sys_organ.ORG_NAME 
FROM
	app_market_dev.MKT_ARES_ETP_INFO ares_etp
	LEFT JOIN app_market_dev.sys_organ sys_organ ON sys_organ.ID = ares_etp.ORG_ID 
WHERE
	ares_etp.TENA_ID = 'T20220820184327017430000000580';


SELECT
	etp_info.ETP_ID,
	etp_info.ETP_NAME 
FROM
	(
SELECT
	ETP_IN.ETP_ID,
	ETP_IN.ETP_NAME, ETP_IN.APP_ID
FROM
	fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN
	inner JOIN app_market_dev.MKT_TENA_INFO_TD TENA_INFO ON ETP_IN.APP_ID = TENA_INFO.CODE 
WHERE
	TENA_INFO.TENA_ID = 'T20231027141354017540000000229' 
	) etp_info
	left JOIN app_market_dev.MKT_ARES_ETP_INFO ares_info ON etp_info.ETP_ID = ares_info.ETP_ID 
WHERE
	ares_info.ETP_ID IS NULL;



SELECT
	t1.id 
FROM
	table1 t1
	LEFT JOIN table2 t2 ON t1.id = t2.id 
WHERE
	t2.id IS NULL;
	
SELECT
	etp_info.* 
FROM
	( SELECT ETP_ID, ETP_NAME FROM T_ENTERPRISE_INFO_TD WHERE APP_ID = 'ZH20231027141308017370000000226' ) etp_info
	LEFT JOIN app_market_dev.MKT_ARES_ETP_INFO ares_info ON etp_info.ETP_ID = ares_info.ETP_ID 
WHERE
	ares_info.ETP_ID IS NULL;



SELECT
	ares_etp.NAME AS ETP_NAME,
	ares_etp.ETP_ID,
	ares_etp.ID,
	pub_industry.INDUSTRY_NAME AS INDUSTRY,
	etp_num.EMP_CNT AS STAFF_SIZE,
	sys_organ.ORG_NAME 
FROM
	app_market_dev.MKT_ARES_ETP_INFO ares_etp
	LEFT JOIN app_market_dev.sys_organ sys_organ ON sys_organ.ID = ares_etp.ORG_ID
	LEFT JOIN fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN ON ETP_IN.ETP_ID = ares_etp.ETP_ID
	LEFT JOIN fuyao_user_dev.ENT_PUB_INDUSTRY_TB pub_industry ON pub_industry.INDUSTRY_CODE = ETP_IN.INDUSTRY_CODE
	LEFT JOIN ( SELECT COUNT( EMP_ID ) AS EMP_CNT, ETP_ID FROM fuyao_user_dev.T_CUSTOM_INFO_TD WHERE VALID != 'I' GROUP BY ETP_ID ) etp_num ON etp_num.ETP_ID = ares_etp.ETP_ID 
WHERE
	ares_etp.TENA_ID = 'T20211022190846016130000000097'


	SELECT DISTINCT
	ETP_IN.ETP_name,
	ETP_IN.ETP_ID AS etpId 
FROM
	fuyao_user_dev.T_ENTERPRISE_INFO_TD ETP_IN
	INNER JOIN app_market_dev.MKT_ARES_ETP_INFO ares_etp ON ETP_IN.ETP_ID = ares_etp.ETP_ID
	INNER JOIN app_market_dev.MKT_TENA_INFO_TD TENA_INFO ON ETP_IN.APP_ID = TENA_INFO.CODE 
WHERE
	TENA_INFO.TENA_ID = 'T20231027141354017540000000229';





SELECT
	Amt AS AMT,
	INDUSTRY,
	ROUND( Amt * 100.0 / TotalAmt, 2 ) AS PERCENTAGE 
FROM
	( SELECT count( etp_id ) AS Amt, INDUSTRY FROM app_market_dev.MKT_ARES_ETP_INFO WHERE TENA_ID = 'T20211025091821016960000000250' GROUP BY INDUSTRY ) AS subquery
	CROSS JOIN ( SELECT count( etp_id ) AS TotalAmt FROM app_market_dev.MKT_ARES_ETP_INFO WHERE TENA_ID = 'T20211025091821016960000000250' ) AS total 
ORDER BY
	INDUSTRY;


SELECT  
    Amt,  
    INDUSTRY,  
    ROUND(Amt * 100.0 / TotalAmt, 2) AS Percentage  
FROM (  
    SELECT  
        count(etp_id) AS Amt,  
        INDUSTRY  
    FROM  
        MKT_ARES_ETP_INFO  
    WHERE  
        TENA_ID = '123'  
    GROUP BY  
        INDUSTRY  
) AS subquery  
CROSS JOIN (  
    SELECT  
        count(etp_id) AS TotalAmt  
    FROM  
        MKT_ARES_ETP_INFO  
    WHERE  
        TENA_ID = '123'  
) AS total  
ORDER BY  
    INDUSTRY;


SELECT
	JX_DATA.ETP_ID,
	sum( JX_DATA.TAX_AMT ) as total_TAX_AMT,
	sum( JX_DATA.INSURANCE_AMT ) as total_INSURANCE_AMT,
	sum( JX_DATA.STAFF_AMT )  as total_STAFF_AMT
FROM
	app_market_dev.MTK_JX_SHOW_DATA_RECORD JX_DATA 
WHERE
	JX_DATA.TENANT_ID = '' 
	AND JX_DATA.OPT_DATE < '' AND JX_DATA.OPT_DATE > '' 
GROUP BY
	JX_DATA.ETP_ID 
ORDER BY
	JX_DATA.ETP_ID;

SELECT
	count( ares.etp_id ) as Amt,
	ares.INDUSTRY 
FROM
	MKT_ARES_ETP_INFO ares 
WHERE
	ares.TENA_ID = '123' 
GROUP BY
	ares.INDUSTRY 
ORDER BY
	ares.INDUSTRY

	