#完全异步模式，需要添加这个属性，并且xml配置logger和root即可，不要开启async，因为没必要
log4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector

#使用disruptor时的bufferSize（2的幂次数是必须的，切记！），默认256*1024，没必要那么大(占用空间)，缩小一些
#https://logging.apache.org/log4j/2.x/manual/async.html#AllAsync
AsyncLogger.RingBufferSize=8192