input {
  file {
    path => ["/usr/local/apache-tomcat-8.0.52/logs/localhost.*.txt","/usr/local/apache-tomcat-8.0.52/logs/localhost_access_log.*.txt","/usr/local/apache-tomcat-8.0.52/logs/catalina.*.txt"]
    start_position => "beginning"
  }
}

filter {
  if [path] =~ "access" {
    mutate { replace => { "type" => "apache_access" } }
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
  }
  date {
    match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
  }
}

output {
  elasticsearch {
    hosts => ["119.29.188.224:9200"]
	user => "elastic"
    password => "changeme"
  }
  stdout { codec => rubydebug }
}